// English translations
import { Rocket, Monitor, ClipboardList, FileText, BarChart3, Users, Map, Building2, Cpu, Package, FolderOpen, Zap, Workflow, Bell, Lock, MessageSquare, Shield, HelpCircle, Smartphone, Settings } from 'lucide-react'

interface SectionItem { q: string; a: string }
interface Section {
 icon: typeof Monitor
 title: string
 path?: string
 items: SectionItem[]
}

const PLATFORM_GUIDE_EN: Section[] = [
 {
 icon: Rocket, title: 'Quick Start',
 items: [
 { q: 'What is ActLedger and what does it do?', a: 'ActLedger is a comprehensive operations management platform that lets you manage all your business processes in one place. It includes task tracking, field reports, KPI measurement, inventory management, IoT integration, live maps, workflows, and AI-powered analytics.\n\nWhen you first log in, your access is determined by the role and department assigned by your administrator. Use the left sidebar to navigate all modules. The top bar provides quick access to notifications, messages, and profile settings.\n\nTo get started:\n1. Click "Cockpit" in the left menu to view your dashboard\n2. Go to "Tasks" to check tasks assigned to you\n3. Set your notification preferences in your profile page\n4. Click the chat bubble at the bottom right to ask OperIQ any question' },
 { q: 'First login and password setup', a: 'Log in with the email address and temporary password provided by your administrator. Enter your email and password on the login screen, then click "Log In".\n\nOn first login, the system will ask you to change your password. Your new password must be at least 8 characters long and contain uppercase, lowercase, numbers, and special characters. After setting your password, log in again to access the platform.\n\nIf you forget your password, click the "Forgot Password" link on the login screen to receive a reset link via email. This link is valid for 24 hours.' },
 { q: 'Left menu and navigation structure', a: 'The main navigation menu is on the left side of the platform. The main sections are:\n\n- Cockpit: Main dashboard and summary views\n- Tasks: Task creation, tracking, and management\n- Reports: Field reports and analytics\n- KPI Panel: Performance indicators and targets\n- Users: Staff and department management\n- Live Map: Location tracking and facility maps\n- IoT Devices: Sensor and device monitoring\n- Inventory: Stock and material management\n- Files: Document and file sharing\n- Automation: Workflows and automated rules\n- Messages: Internal communication system\n\nYou can collapse the menu by clicking the hamburger icon at the top left to expand your workspace. Click again to reopen it.' },
 { q: 'What is the OperIQ AI assistant?', a: 'OperIQ is the AI assistant integrated into ActLedger. It is available throughout the platform. Click the chat bubble in the bottom right corner to start a conversation.\n\nOperIQ can help you with:\n- Asking questions about your tasks and getting summaries\n- Automatically analyzing reports and summarizing findings\n- Creating charts and visualizations\n- Getting inventory status information\n- Interpreting your KPI performance\n- Answering technical questions\n\nOperIQ uses your company-specific data to provide contextual answers. You can ask questions in natural language (Turkish or English). For example, "Which are the most delayed tasks this month?" or "How did the temperature sensor on the production line change in the last 24 hours?"' },
 { q: 'Language and theme settings', a: 'ActLedger supports Turkish and English. To change the language, click your profile icon in the top right corner and select your preferred language. The change applies instantly without page reload.\n\nThe platform uses a light theme. All pages are presented with a consistent, readable design. You can use your browser zoom feature to adjust text size as needed (Ctrl + or Ctrl - shortcuts).' },
 ],
 },
 {
 icon: Monitor, title: 'Cockpit & Dashboard', path: '/panel',
 items: [
 { q: 'How to use the dashboard?', a: 'Click "Cockpit" in the left menu to access the main dashboard. The dashboard provides a single-view summary of your operations, including task statistics, KPI overview, recent reports, notifications, and department-level performance indicators.\n\nYou can create your own layout with draggable widgets. Each widget visualizes a data source as a pie chart, bar chart, number card, list, or map. Use the "+" button at the top right to add new widgets and drag them to reorder.\n\nDashboard data updates in real time by default. You can also refresh manually using the refresh button. Change the date range to view data from different time periods.' },
 { q: 'How to add a new dashboard?', a: 'Select "New Dashboard" from the dropdown next to the dashboard title. Follow these steps:\n\n1. Name your dashboard (e.g., "Weekly Production Summary" or "Field Performance")\n2. Click the add widget button and choose a widget type\n3. For each widget, configure the data source, visualization type, and filters\n4. Drag widgets to arrange them as you like\n5. Click "Save" to store your dashboard\n\nYou can create multiple dashboards and switch between them quickly. For example, one for daily operations and another for weekly management meetings. Dashboards can also be shared with other users.' },
 { q: 'How to create charts with OperIQ?', a: 'Click the "Data Visualization" button. In the popup, describe in natural language what you want to see. OperIQ automatically selects and configures the most suitable chart type.\n\nExample commands:\n- "Task distribution by department" - creates a pie chart\n- "Number of reports in the last 30 days" - creates a line chart\n- "Top 10 departments by KPI performance" - creates a bar chart\n- "Products with critical stock levels" - displays as a table\n\nYou can add the generated chart to your dashboard as a widget, download it as PNG or PDF, or use it directly in a report. OperIQ also provides automated commentary and recommendations about the data.' },
 { q: 'Widget types and features', a: 'Available widget types for your dashboard:\n\n- Number Card: Shows a single metric value in large numbers (e.g., total open tasks, today\'s report count)\n- Pie Chart: Shows proportional distribution (e.g., task status breakdown)\n- Bar Chart: Shows comparative data side by side (e.g., department performance)\n- Line Chart: Tracks changes over time (e.g., weekly task completion trend)\n- Table: Shows detailed data in rows (e.g., overdue tasks list)\n- Map: Shows location-based data on a map (e.g., field team positions)\n\nHover over any widget to reveal edit, resize, and delete buttons in the top right corner. Widget settings let you change the data source, colors, and refresh interval.' },
 { q: 'Dashboard filtering and date range', a: 'Use the filter bar at the top of the dashboard to narrow the displayed data. Available filters:\n\n- Date Range: Today, this week, this month, last 30 days, or custom date range\n- Department: Select to view data for a specific department\n- User: Filter data for a specific user\n- Status: Filter by task or report status\n\nFilters apply to all widgets simultaneously. Click "Reset Filters" to clear them. You can save frequently used filter combinations as saved views.' },
 ],
 },
 {
 icon: ClipboardList, title: 'Task Management', path: '/gorevler',
 items: [
 { q: 'How to create a new task?', a: 'Go to "Tasks" in the left menu and click the "New Task" button at the top right. Fill in the task creation form:\n\n1. Title: Enter a short, clear title describing the task\n2. Description: Write the task details, expected outcomes, and important notes\n3. Department: Select the department the task belongs to\n4. Assignee: Select the person(s) to perform the task (you can assign multiple people)\n5. Priority: Set the priority level - Low, Normal, High, or Critical\n6. Due Date: Select the deadline for the task\n7. Tags: Add tags to categorize the task\n\nAfter creating the task, the assignee receives an automatic notification. All details are visible on the task card and progress can be tracked.' },
 { q: 'How to update task status?', a: 'Click on a task card to open the detail panel. The status field is at the top right with these options:\n\n- Pending: Task has not been started yet\n- In Progress: Task is actively being worked on\n- In Review: Task is completed and awaiting manager approval\n- Completed: Task has been successfully completed\n- Cancelled: Task has been cancelled\n\nWhen the status changes, the system automatically logs a timestamp and notifies relevant people. The task history shows all status changes with dates and times.\n\nYou can also leave comments on the task. Type in the comment field and click "Send". Comments are sent as notifications to all involved parties.' },
 { q: 'How to add a checklist?', a: 'Go to the "Checklist" section in the task detail and add new items. Checklists let you break a task into sub-steps and visually track progress.\n\nTo use checklists:\n1. Open the task detail page\n2. Click "Add New Item" in the Checklist section\n3. Type the item text and press Enter\n4. Add multiple items to define task steps\n5. Check off each completed step - the progress bar updates automatically\n\nChecklist progress is shown as a percentage on the task card. For example, if 4 of 8 items are completed, it shows "50%". This lets you see task progress even from the list view.' },
 { q: 'Task filtering and search', a: 'Use the filter bar above the task list to filter tasks by various criteria:\n\n- Status Filter: Filter by Pending, In Progress, Completed, etc.\n- Priority Filter: Sort by Critical, High, Normal, Low priorities\n- Department Filter: View tasks for specific departments\n- Date Filter: List tasks within a specific date range\n- Assignee: Find tasks assigned to a specific person\n\nType keywords from the task title or description in the search bar for quick search. Filters can be combined - for example, "Critical priority and overdue tasks".' },
 { q: 'Task calendar and timeline', a: 'Switch to "Calendar" view from the view options at the top of the task list. In calendar view, tasks are displayed on their due dates.\n\nAvailable view options:\n- List View: Lists tasks in rows with the most detail visible\n- Kanban View: Shows tasks as cards in status columns - drag and drop to change status\n- Calendar View: Places tasks on a calendar by date\n\nIn Kanban view, drag a task card from one column to another to change its status. For example, dragging from "Pending" to "In Progress" automatically updates the task status.' },
 { q: 'How does the task reply system work?', a: 'Assignees can reply directly on the task to share progress, ask questions, or report issues.\n\nTo reply:\n1. Open the task detail page\n2. Go to the "Reply / Comment" section at the bottom\n3. Write your message, attach files or photos if needed\n4. Click "Send"\n\nReplies are listed chronologically and all relevant parties receive notifications. The manager can review replies and reassign the task if necessary. This system keeps all task-related communication in one place, preventing information loss.' },
 ],
 },
 {
 icon: FileText, title: 'Field Reports', path: '/raporlar',
 items: [
 { q: 'How to create a report?', a: 'Go to "Reports" in the left menu and click "Create New Report". Fill in the form fields:\n\n1. Title: Enter a clear title summarizing the report topic\n2. Description: Describe the situation in detail\n3. Department: Select the relevant department\n4. Priority: Set as Low, Medium, High, or Critical\n5. Tags: Add tags for categorization (separate with commas)\n\nThe report is saved as a "Draft". To submit the draft, click on the report card and press the "Send" button.' },
 { q: 'Managing report statuses', a: 'Each report has a lifecycle:\n\n- Draft: Report is created but not yet submitted. Use "Send" to make it live or "Forward" to send it directly to staff.\n- Sent/Under Review: Report is in the review process. Use "Approve" or "Reject" to take action. Use the "Forward" button to route it to sub-units.\n- Approved: Report has been completed and approved.\n- Rejected: Report has been rejected.\n\nThe report owner receives automatic notifications on each status change.' },
 { q: 'How to forward reports hierarchically', a: 'You can forward reports to sub-units according to the hierarchical structure:\n\n1. Click the "Forward" button in the report detail\n2. A user selection screen opens - Mobile Users and Platform Users are listed in separate groups\n3. Use "Select All" to select everyone, or check individuals\n4. Click "Forward" to send the report\n\nHierarchical workflow:\n- General Manager: Forwards to all departments\n- Department Manager: Forwards to supervisors and sub-units\n- Supervisor: Forwards to field staff (workers, technicians)\n\nForwarded reports appear in the mobile field user\'s "Forms" tab as "Report: ...". Field staff opens the report, takes action (Completed/Issue Found), and adds notes. When completed, relevant platform users receive instant notifications and OperIQ starts automatic analysis.' },
 { q: 'How does OperIQ report analysis work?', a: 'When a report is created and field staff takes action, OperIQ automatically analyzes it:\n\n- Text Analysis: Examines report and field notes to extract key findings\n- Risk Assessment: Evaluates potential impact and urgency level\n- Recommended Actions: Lists actions that should be taken\n- Possible Causes: Analyzes probable root causes\n\nAnalysis results are displayed in the "OperIQ Analysis" section on the report detail page. You can also trigger a manual analysis by clicking the analysis button.' },
 { q: 'Report filtering and history search', a: 'Use the filter tools at the top of the report list to filter reports:\n\n- Date Range: View reports from a specific time period\n- Department: List reports for specific departments\n- Severity: Filter by Critical, High, Medium, or Low severity\n- Status: Filter by Created, Under Review, Resolved, etc.\n- Search: Search for keywords in report titles or content\n\nYou can export reports in Excel format for detailed analysis or management presentations.' },
 { q: 'Attaching files and photos to reports', a: 'The report creation or editing screen includes a file and photo attachment section.\n\nTo add photos:\n- Click "Add Photo"\n- Select files from your computer or drag and drop\n- You can add multiple photos\n- Supported formats: JPG, PNG, GIF, WebP\n- Maximum file size: 10 MB\n\nTo add files:\n- Click "Add File"\n- Select a PDF, Word, Excel, or text file\n- Files are displayed and downloadable in the report detail\n\nUploaded photos appear in a gallery view in the report detail. Click photos to enlarge and browse between them.' },
 ],
 },
 {
 icon: BarChart3, title: 'KPI Management', path: '/kpi-panel',
 items: [
 { q: 'How to define a KPI?', a: 'Go to "KPI Panel" in the left menu. Sector template KPIs are already preloaded. To add new or edit existing KPIs:\n\n1. Click "Add KPI"\n2. Enter the KPI name and description\n3. Select the unit of measurement (percentage, number, duration, amount, etc.)\n4. Set the target value\n5. Select the measurement frequency (daily, weekly, monthly, quarterly)\n6. Assign the relevant department\n7. Select the KPI tier (strategic, tactical, operational, individual, or AI)\n\nOnce defined, the relevant department and users can enter values regularly. Actual values are automatically compared against targets to calculate performance percentage.' },
 { q: 'What are KPI tiers?', a: 'ActLedger offers a 5-tier KPI structure. Each tier serves a different management level:\n\n1. Strategic KPIs (Top Management): Measures overall company performance. Examples: annual revenue growth, customer satisfaction index, market share\n2. Tactical KPIs (Middle Management): Measures department goals. Examples: department efficiency, project completion rate\n3. Operational KPIs (Field): Measures daily operations effectiveness. Examples: daily production output, issue resolution time\n4. Individual KPIs (Personal): Measures individual employee performance. Examples: task completion rate, response time\n5. AI KPIs (OperIQ Generated): Metrics automatically derived from data by OperIQ. Examples: trend analysis, anomaly detection, forecasting scores\n\nYou can filter by tier in the KPI panel to view only the level you are interested in.' },
 { q: 'How to enter KPI actual values?', a: 'Two methods are available for KPI data entry:\n\nManual Entry:\n1. Find the relevant KPI on the KPI Panel page\n2. Click "Enter Value"\n3. Enter the actual value and select the date\n4. Add notes or comments if needed\n5. Click "Save"\n\nBulk Entry (Excel):\n1. Click "Bulk Entry" on the KPI Panel page\n2. Download the template Excel file\n3. Fill in the values in Excel\n4. Upload the file and verify in the preview\n5. Click "Save" to save all values\n\nThe system generates alerts for KPIs without regular data entry and sends reminders to the relevant department manager.' },
 { q: 'KPI performance viewing and reporting', a: 'The KPI panel provides visual performance indicators for each KPI:\n\n- Green-to-red color scale indicates proximity to target\n- Trend arrows show upward or downward direction\n- Graph view tracks changes over time\n\nFor detailed KPI reports:\n- Click a KPI name to open its detail page\n- Review historical data on the graph\n- Compare by department or person\n- View trend predictions with OperIQ analysis\n\nYou can export KPI data in PDF or Excel format. Monthly KPI summary reports are automatically generated and sent to the management team.' },
 { q: 'Sector templates and ready-made KPI sets', a: 'ActLedger offers ready-made KPI templates for 15 different sectors. When your company is created, the appropriate sector template is automatically loaded. These templates are comprehensive libraries containing thousands of KPIs.\n\nEach sector template includes:\n- KPIs grouped by department\n- Pre-defined measurement units and target ranges\n- Sector-specific metrics and terminology\n\nYou can customize template KPIs: change target values, disable unnecessary KPIs, or add new ones. In addition to template KPIs, you can define your own custom KPIs.' },
 ],
 },
 {
 icon: Users, title: 'User & Department Management', path: '/kullanicilar',
 items: [
 { q: 'How to add a new user?', a: 'Click "New User" on the "Users" page. Fill in the user creation form:\n\n1. First and Last Name: Enter the user\'s full name\n2. Email: Enter the email address for login\n3. Phone: Enter the contact phone number\n4. Role: Select one of 8 role levels (detailed below)\n5. Department: Select the user\'s department\n6. Login Code: The system automatically generates a code in ACT-XXXXXX format\n\nOnce created, login credentials with a temporary password are sent via email. The user must change their password on first login. For bulk user creation, use the Excel template.' },
 { q: 'What are the role levels?', a: 'The 8-level permission system works hierarchically. Each level includes all permissions of the levels below it:\n\n1. Worker (Level 1): Can view and complete assigned tasks, fill forms\n2. Technician (Level 2): Can also create reports and view IoT data\n3. Foreman (Level 3): Can create tasks and assign them to their team\n4. Supervisor (Level 4): Can view all tasks and reports in their department, manage stock movements\n5. Chief (Level 5): Can manage department KPIs, create workflows\n6. Manager (Level 6): Can manage multiple departments, add users\n7. Director (Level 7): Can view all departments, create automation rules\n8. General Manager (Level 8): Full access to all modules and settings\n\nBe careful when assigning roles. You can change a user\'s role later.' },
 { q: 'How to create and manage departments?', a: 'For department management, go to the "Departments" tab on the "Users" page. To create a new department:\n\n1. Click "New Department"\n2. Enter the department name\n3. Select a parent department (if any, for hierarchical structure)\n4. Assign a department manager\n5. Select the default KPI set\n6. Click "Save"\n\nThe department hierarchy is displayed as a tree structure. You can create sub-departments under each department. For example, under "Production" you might have "Assembly", "Quality Control", "Packaging", etc.\n\nWhen a department manager is changed, all assignments and permissions are automatically updated.' },
 { q: 'Editing a user profile', a: 'Click a user\'s name in the user list to edit their profile. You can update the following:\n\n- Personal Info: Name, surname, phone, email\n- Role and Department: Permission level and assigned department\n- Profile Photo: User\'s photo\n- Notification Preferences: Which notifications the user receives\n- Password Reset: You can reset the user\'s password\n\nYou can deactivate users instead of deleting them. A deactivated user cannot log in but their historical records are preserved. Use the "Deactivate Account" button.' },
 { q: 'Bulk user import (Excel)', a: 'Use the Excel template upload to add many users at once:\n\n1. Click "Bulk Add" on the "Users" page\n2. Download the blank Excel template with "Download Template"\n3. Fill in the columns: First Name, Last Name, Email, Phone, Department, Role\n4. Upload the completed file\n5. Review in the preview screen - errors are highlighted in red\n6. Click "Create Users" to add all users at once\n\nEach user gets an auto-generated login code and temporary password. You can download a summary file with the login credentials. Distribute this file securely to the relevant people.' },
 ],
 },
 {
 icon: Map, title: 'Live Map', path: '/harita',
 items: [
 { q: 'How to view staff locations?', a: 'On the "Live Map" page, see staff who are actively sharing their location on the map. Each person is shown as a pin - click it to see their name, department, and last location update time.\n\nMap filtering options:\n- Department Filter: View staff in specific departments\n- Status Filter: Filter by active, on break, or offline\n- Time Filter: View locations from the last 1 hour, 4 hours, or 24 hours\n\nStaff locations update every 60 seconds by default. Zoom in and out for different detail levels. Drag the map to focus on a specific area or use the search bar to find an address.' },
 { q: 'How to mark a facility?', a: 'You can mark facility, factory, warehouse, or office locations on the map:\n\n1. Right-click the desired location on the map\n2. Select "Add New Facility"\n3. Enter the facility name and type (Factory, Office, Warehouse, Site, etc.)\n4. Type and confirm the address or use the map location\n5. Choose coordinate format: DMS (degrees-minutes-seconds) or decimal\n6. Click "Save"\n\nFacilities are shown with custom icons on the map. Click a facility icon to see its info, active staff count, and related tasks. You can edit or delete facility info later.' },
 { q: 'Route and movement history', a: 'You can view a staff member\'s daily movements as a route on the map:\n\n1. Click the staff member\'s pin on the map\n2. Click "Route History"\n3. Select the date range\n4. The movements are displayed as a line on the map\n\nRoute history is useful for analyzing field team efficiency and verifying visited locations. The time spent at each stop point is displayed.' },
 { q: 'Map view options', a: 'The map supports different view modes:\n\n- Standard Map: Classic street map view\n- Satellite View: Realistic satellite imagery\n- Terrain View: Includes topographic details\n- Heat Map: Shows staff density as a heat map\n\nClick the layer button in the top right of the map to switch views. Use the measurement tool to measure distance between two points. Use the expand button to open the map in full screen mode.' },
 ],
 },
 {
 icon: Building2, title: 'Facility Map (Live Facility Map)', path: '/harita',
 items: [
 { q: 'How to upload a facility plan?', a: 'On the "Live Operations & Facility Maps" page, go to the "Facility Map" tab. To upload a plan:\n\n1. Click "Upload Plan"\n2. Select a file - supported formats: PNG, JPG, SVG\n3. Enter the plan name and floor info (e.g., "Main Factory - Ground Floor")\n4. Upload the plan and adjust sizing settings\n5. Click "Save" to confirm\n\nYou can upload multiple floor plans. Use the floor selector buttons at the top to switch between floors. After uploading, add zones and markers to create a live facility map.\n\nFor best results, use a high-resolution, clear plan image. SVG format provides the best quality when zooming.' },
 { q: 'How to add zones and markers?', a: 'Activate "Edit" mode and click on the plan to add zones or markers. Steps for adding a zone:\n\n1. Click the "Edit" button to enter editing mode\n2. Click the desired point on the plan\n3. Fill in the zone details in the form:\n - Type: Department, Machine, Warehouse, Office, Common Area, Hazard Zone, etc.\n - Layer: Departments, IoT, Tasks, Inventory, Emergency\n - Color and size settings\n - Linked item: Connect to a Department, IoT device, or stock item\n4. Click "Save" to confirm\n\nCreated zones are displayed with color codes on the plan. Click any zone to view details, monitor live data, and perform quick actions.' },
 { q: 'How to toggle layers on/off?', a: 'Use the layer buttons above the map to control different data layers. Available layers:\n\n- Departments: Shows department zones and staff density\n- IoT: Shows sensor and device locations with live values\n- Tasks: Shows locations of active tasks\n- Inventory: Shows storage locations of stock items\n- Emergency: Shows emergency exits, fire extinguishers, and hazard zones\n\nEach layer can be toggled independently. You can display multiple layers at the same time. Layer selection is done with toggle buttons above the facility map.' },
 { q: 'How to apply a sector template?', a: 'Click the "Template" button to select a ready-made zone layout for your sector. Available template categories:\n\n- Manufacturing: Production lines, quality control, raw material storage, shipping area\n- Logistics: Loading area, vehicle lot, drivers\' room, distribution center\n- Healthcare: Patient reception, operating room, pharmacy, laboratory\n- Retail: Sales floor, warehouse, checkout area, management office\n- Energy: Control room, transformer, generator, maintenance workshop\n- Education: Classrooms, laboratory, library, cafeteria\n\nApplying a template does not affect existing zones - new zones are added. You can later edit, move, or delete template zones as needed.' },
 { q: 'How to view live data?', a: 'Zones linked to IoT devices, departments, or stock items display live status badges. Color codes:\n\n- Green: Normal - all values are within acceptable range\n- Yellow: Warning - some values approaching warning threshold\n- Red: Critical - values exceeded critical threshold, urgent intervention needed\n- Gray: No connection - device is offline or no data received\n\nClick a zone to open the detail panel showing:\n- Live sensor values (temperature, humidity, pressure, etc.)\n- Last 24 hours trend graph\n- Active alarms and warnings\n- Staff list in that zone\n- Related tasks and reports' },
 { q: 'What is emergency mode?', a: 'Click the "Emergency" button to switch the facility map to emergency mode. In this mode:\n\n- Hazard zones are highlighted with bright red borders\n- Emergency exits are marked with green flashing icons\n- Fire extinguishers and first aid kits are displayed\n- Other normal zones appear faded to reduce distractions\n- Critical zones show a pulse animation\n\nEmergency mode helps staff quickly locate exits and safety equipment during an actual emergency. You can also use this mode for drills or planning. Click "Normal Mode" to return to the standard view.' },
 { q: 'How to run OperIQ facility analysis?', a: 'Click the "OperIQ" button to start a comprehensive AI analysis of the entire facility. The analysis includes:\n\n- Space Utilization Analysis: Which zones are actively used, which are idle\n- Risk Assessment: Potential hazard and problem areas\n- Efficiency Recommendations: Workflow and layout optimization suggestions\n- Anomaly Detection: Unusual conditions and warnings\n\nFor a zone-specific analysis, click the zone and press the "OperIQ Analyze" button. Zone-level analysis produces more detailed and focused results.\n\nResults are presented in report format with problem areas, recommended actions, and risk levels. You can create tasks directly from the recommended actions.' },
 ],
 },
 {
 icon: Cpu, title: 'IoT Device Management', path: '/iot',
 items: [
 { q: 'How to add an IoT device?', a: 'Click "New Device" on the "Devices" page and follow these steps:\n\n1. Device ID: Enter the device\'s unique identifier\n2. Device Name: Give it a descriptive name (e.g., "Production Line 1 - Temperature Sensor")\n3. Device Type: Select sensor, gateway, actuator, or controller\n4. Protocol: Select MQTT, HTTP, CoAP, or Modbus\n5. Location: Specify the physical location (you can link it to a zone on the facility map)\n6. Alarm Thresholds: Define min/max thresholds for each measurement\n7. Click "Save"\n\nAfter adding, connection credentials are automatically generated. Use these in your device configuration to start sending data. When the device sends its first data, its status updates to "Online".' },
 { q: 'How to set alarm thresholds?', a: 'In the device detail, define threshold values for each sensor reading. Threshold types:\n\n- Minimum Warning: Yellow warning when value drops below this level\n- Minimum Critical: Red alarm when value drops below this level\n- Maximum Warning: Yellow warning when value exceeds this level\n- Maximum Critical: Red alarm when value exceeds this level\n\nWhen a threshold is breached:\n1. An alarm icon appears in the device detail\n2. The related zone on the facility map turns red/yellow\n3. Designated people receive notifications (email and platform)\n4. If an automation rule is defined, related actions are triggered\n\nYou can update threshold values at any time. View past alarm records in the "Alarm History" tab of the device detail.' },
 { q: 'Device status monitoring and historical data', a: 'Each IoT device\'s detail page includes:\n\n- Live Status: Current device state (online, offline, alarm)\n- Latest Values: Most recent sensor readings\n- Trend Graph: Data chart for the selected time range\n- Connection Info: Last communication time and signal strength\n- Alarm History: All past alarm records\n\nTo view historical data:\n1. Open the device detail page\n2. Go to the "Historical Data" tab\n3. Select the date range\n4. Choose the sensor values you want\n5. The chart is drawn automatically - zoom in for more detail\n\nYou can export historical data in CSV or Excel format.' },
 { q: 'Device grouping and bulk management', a: 'You can organize devices into groups, which is especially helpful for facilities with many devices.\n\nTo create a group:\n1. Go to the "Groups" tab on the "Devices" page\n2. Click "New Group"\n3. Enter a group name (e.g., "Production Line Sensors", "Warehouse HVAC")\n4. Add devices to the group\n5. Click "Save"\n\nYou can perform bulk operations on groups: update alarm thresholds in bulk, enable/disable all devices, or monitor the group\'s overall health on a single screen. Use the group filter in the device list to quickly find devices in a specific group.' },
 { q: 'IoT data visualization', a: 'Visualize IoT data with various chart types:\n\n- Line Chart: Track changes in time series (e.g., temperature trend)\n- Gauge: View the current value on a dial\n- Heat Map: Compare multiple device values using a color matrix\n- Table: View all device values in rows\n\nTo add an IoT widget to a dashboard, use the "IoT Widget" option in dashboard editing mode. Each widget can show data from one or multiple devices. Real-time updates keep the data streaming live.' },
 ],
 },
 {
 icon: Package, title: 'Inventory Management', path: '/stok',
 items: [
 { q: 'Inventory module overview', a: 'The inventory management module tracks all materials, raw materials, spare parts, and products in your business. The main screen shows:\n\n- Inventory Summary: Total item count, total value, items at critical levels\n- Category Distribution: Chart of inventory distribution by category\n- Recent Movements: Latest inbound and outbound transactions\n- Alerts: Items that have fallen below minimum stock level\n\nUse the category tree on the left for quick access to specific categories. The search bar at the top lets you search by item name, code, or barcode number.' },
 { q: 'How to add a new stock item?', a: 'Click "New Item" on the inventory page to add a stock item:\n\n1. Item Name: Enter the product or material name\n2. Stock Code: Assign a unique stock code (auto-generation available)\n3. Category: Select a category or create a new one\n4. Unit: Select unit type - piece, kg, liter, meter, box, etc.\n5. Minimum Stock Level: Set the lower limit for alerts\n6. Maximum Stock Level: Set the upper limit (optional)\n7. Warehouse/Location: Select the physical storage location\n8. Barcode: Enter the barcode number if available\n9. Supplier: Select the default supplier\n\nAfter creation, you can add photos, additional notes, and mark the location on the facility map.' },
 { q: 'How to record stock movements (in/out)?', a: 'Two methods for recording stock movements:\n\nSingle Item Movement:\n1. Open the stock item detail page\n2. Click "Add Movement"\n3. Select movement type: Inbound (purchase, return, production) or Outbound (usage, shipment, waste)\n4. Enter the quantity\n5. Add a description and reference number\n6. Click "Save" to confirm\n\nBulk Movement:\n1. Click "Bulk Movement" on the inventory page\n2. Download the Excel template or scan items with a barcode reader\n3. Specify quantity and movement type for each item\n4. Review the preview\n5. Click "Confirm" to save all movements\n\nEach movement is recorded with an automatic timestamp and user info. Movements cannot be reversed - create a counter-movement for corrections.' },
 { q: 'How do stock alerts work?', a: 'When an item with a defined minimum stock level falls below that level, an automatic alert is triggered. The alert system works as follows:\n\n1. Stock quantity drops below the minimum level\n2. System creates an alert and notifies relevant people\n3. The item is highlighted in red under "Critical Stock" in the inventory panel\n4. An alert appears in the stock widget on the dashboard\n5. If an automation rule is defined, an automatic purchase request can be created\n\nAlert levels:\n- Yellow Warning: Stock is approaching minimum level (minimum + 20%)\n- Red Alarm: Stock has dropped below minimum level\n- Zero Stock: Stock is completely depleted\n\nYou can configure who receives alert notifications in the inventory settings.' },
 { q: 'How to import inventory (Excel/CSV)?', a: 'To bulk import your existing inventory:\n\n1. Click "Import" on the "Inventory" page\n2. Download the blank template with "Download Template"\n3. Fill the template in Excel or CSV format. Required fields: Item Name, Stock Code, Category, Unit, Quantity\n4. Upload the completed file\n5. OperIQ auto-matches columns - check the matching preview\n6. Errors are shown with correction suggestions\n7. Click "Save" to import all items\n\nYou can also use this method to update existing stock items - items with matching stock codes are updated, new codes are added as new items.' },
 { q: 'Inventory reports and analysis', a: 'Various reports and analyses are available in the inventory module:\n\n- Stock Status Report: Current quantities and values of all items\n- Movement Report: All inbound and outbound movements for a date range\n- Consumption Analysis: Consumption rate and trends for items\n- Critical Stock Report: Items below or approaching minimum level\n- Value Report: Stock value distribution by category\n\nReports can be downloaded in PDF or Excel format. Use OperIQ for forecasting and optimization based on your inventory data - for example, ask "Which items might run out next month?"' },
 ],
 },
 {
 icon: Package, title: 'AssetIQ (QR + Inventory Intelligence)', path: '/envanter-zeka',
 items: [
 { q: 'What is the AssetIQ module?', a: 'AssetIQ is an AI-powered inventory and consumption management system that deeply integrates QR code tracking with inventory management and operational processes.\n\nCore features include:\n- QR Code Management: Generate and scan QR codes for every stock item and location\n- Stock Locations: Hierarchical warehouse/shelf/compartment structure\n- Batch/Lot Tracking: Production date, expiry date, supplier info\n- Advanced Movements: 7 movement types (Inbound, Outbound, Usage, Waste, Transfer, Count, Reservation)\n- Task-Based Stock Allocation: Reserve stock for specific tasks\n- Quick Consumption: One-tap stock deduction for field workers\n- OperIQ Analysis: Sector-specific AI-powered inventory analysis\n- Procurement Contact: Ensuring critical stock alerts reach the right people' },
 { q: 'How to create and use QR codes?', a: 'To create QR codes:\n1. Go to the "QR Management" tab in AssetIQ\n2. Click "New QR"\n3. Select the asset type (Stock Item, Location, Equipment, IoT Device, Facility Zone)\n4. Select the linked asset\n5. Add optional tags\n6. Click "Generate QR"\n\nTo scan a QR:\n- Enter the QR code in the "Scan QR" section or scan it from the mobile app\n- The system automatically opens the linked asset\n- Sector-appropriate screens and actions are displayed\n\nExamples:\n- In manufacturing: scanning opens machine-linked parts screen\n- In healthcare: scanning opens medication/medical supplies screen\n- In retail: scanning opens shelf stock screen' },
 { q: 'How to manage stock locations?', a: 'Locations are organized in a hierarchical structure (Warehouse > Shelf > Compartment).\n\n1. Go to the "Locations" tab\n2. Click "New Location"\n3. Enter location info: Name, Code, Category, Department\n4. Select a parent location to create sub-locations\n\nLocation categories:\n- Main Warehouse, Shelf, Production Line, Cold Storage, Maintenance Depot, Vehicle, Distribution Point, Service Area, Laboratory\n\nStock items and quantities at each location can be viewed. The location tree view shows the entire structure at a glance.' },
 { q: 'How does batch/lot tracking work?', a: 'Batch/lot management is especially critical in food, healthcare, chemical, and FMCG sectors.\n\n1. Go to the "Batch/Lot" tab\n2. Click "New Batch"\n3. Select the stock item\n4. Enter the batch number (e.g., LOT-2026-001)\n5. Enter production date and expiry date\n6. Add supplier and location info\n\nThe system automatically:\n- Flags batches nearing expiry (30 days) as warnings\n- Updates status of expired batches\n- Shows "Batches Nearing Expiry" list on the dashboard' },
 { q: 'How to use quick consumption mode?', a: 'Quick stock deduction with minimal input for field workers:\n\n1. Scan the QR code or click "Quick Consumption"\n2. Select the stock item\n3. Choose quantity (+1, +5, +10, or custom amount)\n4. Click "Save" for one-tap stock deduction\n\nQuick consumption automatically:\n- Records an InventoryTransaction\n- Creates a ConsumptionEvent\n- Updates StockMovement (legacy)\n- Checks critical levels and triggers alerts if needed\n\nThis feature is labeled differently by sector (manufacturing: "Quick Usage", healthcare: "Quick Supply Deduction", retail: "Quick Shelf Deduction").' },
 { q: 'How to reserve stock?', a: 'Stock reservation for tasks:\n\n1. Go to the "Reservations" tab\n2. Click "New Reservation"\n3. Select the stock item and quantity\n4. Specify which task it is for\n5. Add an expiry date (optional)\n\nReservations do not deduct from stock quantity but are factored into available quantity calculations. When the task is completed, the reservation is automatically consumed. Expired reservations are automatically closed.' },
 { q: 'How to assign a procurement contact?', a: 'To ensure critical stock alerts reach the right people:\n\n1. Go to the "Procurement" tab\n2. Click "Add Contact"\n3. Select the user\n4. Set the responsibility type: Primary Procurement Contact, Backup Contact, or Key Account Manager\n5. Select responsible departments (leave empty to cover the entire company)\n\nWhen stock is critical or at risk:\n- The department manager of the affected stock receives a notification and message\n- Relevant procurement contacts receive a notification and message\n- If there is no procurement department, the key account manager is notified' },
 { q: 'Sector templates and terminology', a: 'AssetIQ offers adaptable terminology for 10 different sectors:\n\n1. Manufacturing: Spare Parts, Consumables, Production Line\n2. Food: Raw Materials, Packaging, Cold Storage, Batch/Lot\n3. Healthcare: Medical Supplies, Medication, Pharmacy, Patient Usage\n4. Logistics: Carton, Pallet, Shipment Dispatch, Distribution Point\n5. Retail: Product, Shelf Stock, Sales Dispatch, Store Warehouse\n6. Public: Equipment, Technical Materials, Service Building\n7. Education: Training Materials, Lab Consumables\n8. Energy: Critical Parts, Transformer Site, Maintenance Usage\n9. HoReCa: Kitchen Consumables, Service Materials, Cold Room\n10. IT: Network Equipment, Server Room, Installation Dispatch\n\nWhen your company\'s sector is selected, all screens, movement names, and OperIQ interpretations automatically adapt to the sector language.' },
 { q: 'IoT device contact and notification system', a: 'One or more contacts can be assigned to each IoT device:\n\n1. Go to the "IoT Contact" section\n2. Select the device and the responsible person\n3. Set the responsibility type (Primary or Backup)\n4. Configure notification preferences:\n - Notify on alert status\n - Notify on critical status\n - Notify on offline status\n - Routine status report (twice daily: 09:00 and 17:00)\n\nIn risk or critical situations, the responsible person receives automatic notifications and messages. Twice daily, all contacts receive a general status summary of the devices they are responsible for.' },
 { q: 'OperIQ inventory analysis', a: 'OperIQ analyzes stock data in your sector context:\n\n1. Go to the "OperIQ Intelligence" tab\n2. Click "Analyze"\n3. The system performs these analyses:\n - Fast-depleting items and risk assessment\n - Abnormal consumption patterns\n - Depletion forecast (how many days remaining)\n - Batch/lot expiry risks\n - IoT device status correlated with stock\n - Excess stock detection\n - Task-stock compatibility\n - Supply planning recommendations\n\nEach insight is action-oriented and presented in sector terminology. For example, in manufacturing: "Bearing consumption increased 40% in the last 10 days", in healthcare: "This medical supply is being consumed faster than expected".' },
 ],
 },
 {
 icon: FolderOpen, title: 'File Management', path: '/dosyalar',
 items: [
 { q: 'How to upload files?', a: 'The file management module lets you organize all your corporate documents. To upload files:\n\n1. Go to "Files" in the left menu\n2. Navigate to the folder you want (or create a new one)\n3. Click "Upload File" or drag and drop files directly\n4. Supported formats: Word (.docx), Excel (.xlsx), PDF (.pdf), images (JPG, PNG, GIF), text (.txt, .csv)\n5. Maximum file size: 50 MB\n6. You can upload multiple files at once\n\nEach uploaded file automatically records the uploader, date, and size. Add descriptions and tags to files to improve searchability.' },
 { q: 'Folder structure and organization', a: 'Organize your files using a folder hierarchy:\n\n1. Click "New Folder"\n2. Enter the folder name\n3. Select a parent folder (to create a sub-folder)\n4. Set access permissions (all users or specific departments)\n\nRecommended folder structure:\n- General Documents: Company-wide shared files\n- Department Files: Separate folder for each department\n- Project Files: Project-specific documents\n- Templates: Form templates and standard documents\n- Archive: Old and completed project files\n\nYou can drag folders to move them, rename them, or delete them (contents are moved to the recycle bin).' },
 { q: 'File viewing and preview', a: 'Click a file name to view its content within the platform. Preview-supported formats:\n\n- PDF: Page-by-page viewing, zoom, search\n- Word (.docx): Document content displayed with formatting\n- Excel (.xlsx): Table view with sheet tabs\n- Images (JPG, PNG, GIF): Full-size viewing, zoom\n- Text Files (.txt, .csv): Displayed as plain text\n\nAvailable actions in the preview screen:\n- Download: Download the file to your computer\n- Share: Share the file link with other users\n- Print: Send the file directly to a printer\n- Delete: Move the file to the recycle bin' },
 { q: 'File search and filtering', a: 'Search features in the file module:\n\n- Quick Search: Type the file name in the search bar at the top\n- Type Filter: Filter by specific file types (PDF, Excel, Image, etc.)\n- Date Filter: Find files uploaded within a specific time range\n- Uploaded By: List files uploaded by a specific user\n- Tag: Filter by tags added to files\n\nSearch results include file name, size, upload date, and location. Click a result to view the file directly.' },
 ],
 },
 {
 icon: Zap, title: 'Automation & Rules', path: '/otomasyon',
 items: [
 { q: 'How to create an automation rule?', a: 'Use the step-by-step wizard on the "Automation" page to define rules:\n\n1. Select a Trigger: Choose the event that starts the rule\n - Task overdue\n - Report created\n - Stock level dropped\n - IoT alarm triggered\n - KPI target exceeded or declined\n - Specific time reached (scheduled)\n\n2. Add a Condition (optional): Define when the trigger should fire\n - Department filter\n - Priority level\n - Specific user or role\n\n3. Define an Action: Specify what happens when triggered\n - Send notification (platform, email)\n - Create task\n - Update status\n - Create report\n - Start OperIQ analysis\n\n4. Test and activate the rule\n\nExample: "If a critical priority task is overdue by 24 hours, send an email to the department manager and a notification to upper management"' },
 { q: 'Managing automation rules', a: 'Manage existing rules from the rule list on the "Automation" page:\n\n- Active/Inactive: Toggle each rule on or off with the switch next to it\n- Edit: Click a rule row to modify its details\n- Duplicate: Copy an existing rule to create a similar new one\n- Delete: Remove rules that are no longer needed\n- Execution History: Each rule\'s trigger times and outcomes are logged\n\nRules are processed in priority order. If multiple rules share the same trigger, all of them run independently. Review rule execution history to detect unexpected behavior.' },
 { q: 'Ready-made automation templates', a: 'Use ready-made automation templates to get started quickly. The "Templates" section on the left has common scenarios:\n\n- Task Overdue Alert: Automatic notification for overdue tasks\n- Critical Report Escalation: Routing critical severity reports to upper management\n- Stock Replenishment Request: Purchase request for items below minimum stock\n- IoT Alarm Response: Create a task when a sensor alarm is triggered\n- Weekly Summary: Generate a weekly summary report every Monday\n\nSelect a template, configure the settings (departments, people, etc.), and click "Activate". You can also use templates as a base to create your own custom rules.' },
 { q: 'Automation logs and debugging', a: 'Each automation rule creates a detailed log entry when it runs. To review logs:\n\n1. Click the relevant rule on the Automation page\n2. Go to the "Execution History" tab\n3. Each run shows the date, trigger info, condition result, and action status\n\nLog statuses:\n- Success (green): Rule ran successfully and action completed\n- Skipped (yellow): Rule was triggered but condition was not met\n- Error (red): Rule ran but action failed\n\nReview error details to diagnose issues. Common errors: target user not found, email could not be sent, or target resource does not exist.' },
 ],
 },
 {
 icon: Workflow, title: 'Workflows', path: '/otomasyon',
 items: [
 { q: 'What are workflows and what are they for?', a: 'Workflows let you digitize multi-step business processes that must follow a specific sequence. For example, a procurement process might include: request creation, chief approval, manager approval, purchasing, receiving, quality control.\n\nBenefits of workflows:\n- Processes are standardized and everyone follows the same steps\n- It is clear who does what at each step\n- Approval mechanisms provide control\n- Real-time visibility into which stage the process is at\n- Automatic reminders for delayed steps\n- Historical records enable performance analysis' },
 { q: 'How to create a new workflow?', a: 'Click "New Workflow" on the "Workflows" page. The workflow designer opens. Steps:\n\n1. Workflow Name: Give it a descriptive name (e.g., "Purchase Request", "Leave Application")\n2. Start Condition: Choose how the workflow is initiated (manual or auto-trigger)\n3. Add Steps: For each step define:\n - Step name and description\n - Responsible person or role (e.g., "Department Manager")\n - Step type: Approval, Data Entry, Notification, Branch, or Parallel Task\n - Completion time (optional SLA)\n4. Define Connections: Set the order of step progression\n5. Branching: Define one path for "Approved" and another for "Rejected"\n6. Click "Save and Activate" to publish\n\nUse drag-and-drop in the workflow designer to add steps and change their order.' },
 { q: 'Workflow templates', a: 'Ready-made workflow templates are available for a quick start:\n\n- Purchase Request: Request - Chief Approval - Manager Approval - Procurement - Receiving\n- Leave Application: Application - Manager Approval - HR Approval - Record\n- Maintenance Request: Issue Report - Prioritization - Assignment - Execution - Inspection\n- New Employee Onboarding: Document Collection - HR Registration - IT Account Setup - Training - Department Assignment\n- Quality Control: Sampling - Testing - Evaluation - Approve/Reject\n\nTo use a template:\n1. Click "New Workflow"\n2. Go to the "Create from Template" tab\n3. Select the template you want\n4. Customize the steps for your needs\n5. Save and activate\n\nTemplates are a good starting point - add and modify steps to match your own processes.' },
 { q: 'Tracking running workflow instances', a: 'Track active workflow instances in the "Running Workflows" tab on the Workflows page. It shows:\n\n- Workflow Name and Initiator\n- Current Step: Which stage the process is at\n- Responsible Person: Who is expected to take action\n- Start Date and Duration\n- Status: In Progress, Completed, Pending, Cancelled\n\nClick an instance to see the detailed timeline: who did what and when at each step, time spent, and any added notes.\n\nYou receive a notification if a step is waiting for you. Click the step to approve, reject, or enter information.' },
 { q: 'Workflow reports and performance', a: 'Access these reports to analyze workflow performance:\n\n- Average Completion Time: Average completion time for each workflow type\n- Bottleneck Analysis: Longest steps and wait points\n- Completion Rate: Ratio of successfully completed vs. cancelled workflows\n- Per-Person Performance: Each user\'s approval/rejection time and count\n\nThese reports help you identify inefficiencies in your processes and make improvements. Ask OperIQ "Where are the bottlenecks in my workflows?" for AI-powered analysis.' },
 ],
 },
 {
 icon: Bell, title: 'Notifications',
 items: [
 { q: 'How to view notifications?', a: 'There are multiple ways to access notifications:\n\n- Top Bar: Click the bell icon at the top right - unread notifications show a red badge\n- Notification Panel: Click the bell icon to open a panel listing recent notifications\n- Notification Page: Click "View All Notifications" to see the full notification list\n\nNotification types:\n- Task Notification: New task assigned, status change, comment added\n- Report Notification: New report, status update, OperIQ analysis result\n- IoT Alarm: Sensor threshold breach, device offline warning\n- Stock Alert: Below minimum stock level\n- Workflow: Step awaiting approval, workflow completed\n- System: Platform update, maintenance announcement' },
 { q: 'Setting notification preferences', a: 'Configure which notifications you receive and how in your profile settings:\n\n1. Click your profile icon at the top right\n2. Go to "Notification Preferences"\n3. For each notification category, set the channel:\n - Platform Notification: Via the bell icon in the top bar\n - Email: Sent to your login email\n - Both: Receive via both platform and email\n - Off: Do not receive notifications for this category\n\nCategories: Tasks, Reports, IoT Alarms, Stock Alerts, Workflows, Messages, System Announcements\n\nTip: We recommend keeping both platform and email notifications enabled for critical IoT alarms and task assignments. For lower-priority items, platform-only notifications may be sufficient.' },
 { q: 'Marking notifications as read', a: 'You can manage notifications with these actions:\n\n- Single Notification: Click a notification to automatically mark it as read and navigate to the relevant page\n- Bulk Mark: Click "Mark All as Read" at the top of the notification panel to mark everything read\n- Filtering: Use the "Unread" filter on the notification page to see only new notifications\n- Delete: Delete old notifications individually or in bulk\n\nThe unread notification count is shown in a red badge next to the bell icon in the top bar. Regularly checking your notifications helps you avoid missing important tasks.' },
 { q: 'Email notifications and summaries', a: 'In addition to in-platform notifications, you can receive updates via email:\n\n- Instant Email: Sent immediately for critical notifications\n- Daily Summary: Sent every morning at 08:00 with the previous day\'s summary\n- Weekly Summary: Sent every Monday morning with the weekly performance summary\n\nYou can enable or disable email notifications in your profile settings. Use the "Go to Platform" button in emails to navigate directly to the relevant page.\n\nNote: A valid registered email address is required for email notifications. Check your spam folder as well.' },
 ],
 },
 {
 icon: Lock, title: 'Security & Authorization',
 items: [
 { q: 'How does the permission system work?', a: 'ActLedger\'s permission system is built on an 8-level hierarchy. The role assigned to each user determines what they can see and do on the platform.\n\nKey principles:\n- Each upper level automatically includes all permissions of lower levels\n- Department-based access restriction applies - users see only their own department\'s data (except manager roles)\n- Some actions (adding users, creating automations, changing settings) are only available at certain role levels\n- All access and actions are logged (audit trail)\n\nRole assignment is done by the Super Admin or General Manager. To change a user\'s role, edit their profile from the "Users" page.' },
 { q: 'What can each role do?', a: 'Detailed role permissions:\n\nWorker (Level 1):\n- Can view and complete assigned tasks\n- Can fill forms\n- Can view own profile\n\nTechnician (Level 2):\n- Plus create field reports\n- View IoT data (read-only)\n\nForeman (Level 3):\n- Can create tasks and assign to their team\n- View inventory\n\nSupervisor (Level 4):\n- Can view all tasks and reports in their department\n- Can perform stock movements\n- Can upload and share files\n\nChief (Level 5):\n- Can manage department KPIs\n- Can create workflows\n- Can approve reports\n\nManager (Level 6):\n- Can manage multiple departments\n- Can add users\n- Can create automation rules\n\nDirector (Level 7):\n- Full access to all departments\n- Facility map management\n- Advanced reporting\n\nGeneral Manager (Level 8):\n- Full access to all modules and system settings' },
 { q: 'Password security and policies', a: 'ActLedger enforces strong password policies:\n\n- Minimum 8 characters\n- At least 1 uppercase, 1 lowercase, 1 number, and 1 special character\n- Reuse of the last 5 passwords is blocked\n- Password change reminder every 90 days\n\nPassword security tips:\n- Avoid easily guessable passwords (birthdate, name, "123456", etc.)\n- Use a different password for each platform\n- Do not share your password with anyone\n- Consider using a password manager\n\nIf you forget your password, use the "Forgot Password" link on the login screen. The reset link sent to your email is valid for 24 hours. After 5 failed login attempts, your account is temporarily locked - wait 15 minutes or ask your administrator to unlock it.' },
 { q: 'Session security and logout', a: 'Platform session security works as follows:\n\n- Auto Logout: Session automatically ends after 30 minutes of inactivity\n- Multi-Device Policy: The same account can log in from multiple devices, each tracked as a separate session\n- Secure Logout: Click "Log Out" from the profile menu at the top right to safely end your session\n\nIf you notice suspicious login activity:\n1. Change your password immediately\n2. Notify your administrator\n3. Use "Close All Sessions" to end sessions on other devices\n\nThe platform logs every login with date, time, IP address, and device information. These records are retained for security auditing.' },
 ],
 },
 {
 icon: MessageSquare, title: 'Messaging',
 items: [
 { q: 'How to send a message?', a: 'Click the message icon in the top menu or go to "Messages" in the left menu. Steps to send a message:\n\n1. Click "New Message"\n2. Select a recipient by searching by name or department in the directory\n3. You can add multiple recipients (group message)\n4. Write your message\n5. Attach files if needed (images, documents, etc.)\n6. Click "Send" or use the Ctrl+Enter shortcut\n\nMessages are delivered instantly and the recipient receives a notification. You can view sent messages in the "Sent" folder.' },
 { q: 'Message history and search', a: 'All your messages are stored as conversations. Your entire correspondence with a person is displayed chronologically.\n\nTo search messages:\n- Type a keyword in the search bar at the top of the Messages page\n- Results list message content and sender/recipient info\n- Click a result to navigate to the relevant conversation\n\nTo delete a message, right-click it and select "Delete". Deleted messages are only removed from your view and remain in the recipient\'s history.' },
 { q: 'Group messages and department communication', a: 'Use group messaging to send messages to multiple people at once:\n\n1. Click "New Message"\n2. Select multiple people in the recipient field, or type a department name to add the entire department\n3. Write and send your message\n4. All recipients can see the message and replies\n\nFor department-level messaging, select the department name as the recipient - all users in that department receive the message. This feature is very useful for announcements and general updates.' },
 { q: 'Attaching files and media to messages', a: 'Click the attachment icon in the message composition area or drag a file directly into the message field.\n\nSupported file types:\n- Images: JPG, PNG, GIF (displayed as preview)\n- Documents: PDF, Word, Excel (displayed as download link)\n- Other: Text files, CSV files\n\nMaximum file size: 25 MB. You can attach multiple files. Images appear as small previews in the message and open in full size when clicked.' },
 ],
 },
 {
 icon: Shield, title: 'Shortcuts & Tips',
 items: [
 { q: 'What are the keyboard shortcuts?', a: 'Press "?" to view the shortcut list. All key shortcuts:\n\nNavigation Shortcuts:\n- g + d: Go to Dashboard (Cockpit)\n- g + t: Go to Tasks\n- g + r: Go to Reports\n- g + k: Go to Users\n- g + h: Go to Map\n- g + s: Go to Inventory\n- g + i: Go to IoT Devices\n- g + m: Go to Messages\n\nAction Shortcuts:\n- n: Create new (task, report, etc. depending on current page)\n- /: Focus the search bar\n- Esc: Close open window or panel\n- Ctrl + Enter: Submit form or send message\n\nUsing these shortcuts lets you navigate the platform quickly without a mouse.' },
 { q: 'Tips for using the platform efficiently', a: 'Apply these tips to improve your experience:\n\n- Customize your dashboard: Add the data you check most frequently as widgets\n- Save filters: Save frequently used filter combinations for one-click access\n- Learn shortcuts: Keyboard shortcuts make your work much faster\n- Use OperIQ: Ask the AI assistant complex questions in natural language\n- Configure notifications: Turn off unnecessary notifications to reduce distractions\n- Install the mobile app: Complete tasks and send reports from the field using the mobile app\n- Regular data entry: Keep KPI values and stock movements up to date - automation rules depend on accurate data' },
 { q: 'Browser compatibility and recommendations', a: 'ActLedger performs best on these browsers:\n\n- Google Chrome (recommended) - latest version\n- Mozilla Firefox - latest version\n- Microsoft Edge - latest version\n- Safari (macOS) - latest version\n\nFor the best experience:\n- Always keep your browser up to date\n- Make sure JavaScript is enabled\n- Ensure your pop-up blocker has whitelisted the ActLedger domain\n- Minimum 1280x720 screen resolution recommended\n- Stable internet connection (at least 2 Mbps) required' },
 { q: 'Getting help and support', a: 'When you encounter issues or need help, use these resources:\n\n- This Guide: The "User Guide" page in the left menu (you are here now)\n- OperIQ Assistant: Click the chat bubble at the bottom right to ask the AI assistant\n- Support Request: Create a support ticket from the "Support" section in the profile menu\n- Email Support: Send an email to the support team for technical issues\n\nIncluding the following info in your support request speeds up resolution:\n- Describe what the issue is and when it started\n- Specify which page or module is affected\n- Attach a screenshot (if possible)\n- Note which browser and device you are using' },
 ],
 },
 {
 icon: HelpCircle, title: 'Frequently Asked Questions (FAQ)',
 items: [
 { q: 'How to help a user who forgot their password?', a: 'The user can reset their password using the "Forgot Password" link. If they cannot access their email, an administrator (Manager level or above) can click "Reset Password" on the user\'s profile to generate a new temporary password. The temporary password is shared with the user and must be changed on first login.\n\nNote: You cannot view existing passwords for security reasons - you can only generate a new temporary password.' },
 { q: 'Is there a risk of data loss? How does backup work?', a: 'ActLedger keeps your data safe with an automatic backup system:\n\n- Database backup: Automatic daily backups\n- File backup: All uploaded files are stored with redundancy\n- Data retention: Deleted data can be recovered for 30 days\n\nAll changes are saved instantly. If internet connectivity drops, data in the mobile app is stored on the device and automatically synced when connectivity returns. The risk of data loss is minimal.' },
 { q: 'I am experiencing errors or slowness, what should I do?', a: 'If you experience performance issues, try these steps:\n\n1. Browser Cache: Clear your browser cache with Ctrl+Shift+Delete\n2. Refresh Page: Press F5 or Ctrl+R to reload\n3. Different Browser: Try a different browser (Chrome recommended)\n4. Internet Connection: Check your connection speed (at least 2 Mbps)\n5. Extensions: Temporarily disable browser extensions\n6. Device: Restart your computer\n\nIf the issue persists, create a support request including: which page the issue occurs on, when it started, and your browser name and version.' },
 { q: 'Can I assign tasks to multiple departments?', a: 'Yes, you can select people from multiple departments when creating a task. A task can be assigned to multiple people, and each assignee sees the task in their task list.\n\nCross-department task assignment requires sufficient permission level. Normally, a user can only assign tasks to people in their own department. To assign across multiple departments, you need at least the Manager (Level 6) role or higher.\n\nYou can add or remove assignees from the "Assignees" section in the task detail.' },
 { q: 'How current is the OperIQ analysis?', a: 'OperIQ uses your platform data in real time. When you request an analysis, it considers all currently available data including IoT data, task statuses, stock levels, and reports.\n\nThe depth of analysis OperIQ can provide depends on how much data exists on the platform. The longer the platform has been in use and the more data entered, the more detailed and accurate the analyses will be.\n\nThe daily photo analysis limit is 5 per day in the mobile app. There is no limit for text-based queries on the platform.' },
 { q: 'Bulk data upload via Excel or CSV is failing, what should I do?', a: 'If you encounter issues with bulk data upload, check the following:\n\n- File Format: Ensure your file is in .xlsx or .csv format (.xls is not supported)\n- Column Headers: Do not modify the column headers from the template\n- Empty Rows: Do not leave blank rows between data\n- Special Characters: Make sure there are no unexpected special characters in the data\n- File Size: Maximum file size is 10 MB\n- Row Limit: Maximum 5,000 rows can be uploaded at once\n\nErrors are highlighted in red in the preview screen with error descriptions. Fix the flagged rows and try again. OperIQ also offers automatic correction suggestions during column matching.' },
 ],
 },
]

const MOBILE_GUIDE_EN: Section[] = [
 {
 icon: Smartphone, title: 'Login & Getting Started',
 items: [
 { q: 'How to log in on mobile?', a: 'Log in with the login code (ACT-XXXXXX) and temporary password provided by your admin. On the login screen:\n\n1. Enter your ACT-XXXXXX code in the "Login Code" field\n2. Enter your temporary password in the "Password" field\n3. Tap "Log In"\n4. On first login, the system will ask you to set a new password\n5. Enter and confirm your new password\n\nYour password must be at least 8 characters long and include uppercase, lowercase, and numbers. Do not share your login code or password. If you forget your password, request a new temporary one from your administrator.' },
 { q: 'What is on the app home screen?', a: 'The mobile app has a simple, easy-to-use interface. Main components:\n\nBottom Menu (4 tabs):\n- Tasks: All tasks assigned to you and their statuses\n- Forms: Field forms you need to fill out\n- OperIQ Assistant: AI chat screen\n- Profile: Personal info, settings, and logout\n\nTop Bar:\n- Sync Button: Syncs data with the server (green = up to date, orange = pending data)\n- Notification Bell: New notifications and alerts (red dot = unread notifications)\n- Company Logo: Return to home screen\n\nThe home screen also shows a daily summary: pending task count, tasks completed today, and important notifications.' },
 { q: 'Adding the app to home screen (PWA)', a: 'The ActLedger mobile app runs as a Progressive Web App (PWA). No app store download is needed. To add it to your home screen:\n\niPhone / Safari:\n1. Open the ActLedger mobile URL in Safari\n2. Tap the share icon (square with arrow) in the bottom menu\n3. Select "Add to Home Screen"\n4. Tap "Add"\n\nAndroid / Chrome:\n1. Open the ActLedger mobile URL in Chrome\n2. Tap the three-dot menu icon at the top\n3. Select "Add to Home screen"\n4. Tap "Add"\n\nOnce added, the app appears as an icon like other apps and runs in full-screen mode.' },
 { q: 'Setting up notification permissions', a: 'To receive push notifications from the mobile app, you need to grant notification permission on your device. The app will request permission on first login.\n\nTo grant permission:\n- iPhone: Tap "Allow". You can adjust later via Settings > Notifications > ActLedger.\n- Android: Tap "Allow". You can adjust later via Settings > Apps > ActLedger > Notifications.\n\nOnce permission is granted, you will receive instant notifications when:\n- A new task is assigned to you\n- A task status changes\n- A new message arrives\n- A workflow step is waiting for your approval' },
 ],
 },
 {
 icon: ClipboardList, title: 'Tasks',
 items: [
 { q: 'How do I view my tasks?', a: 'The "Tasks" tab lists all active tasks assigned to you. Each task card shows:\n\n- Task Title\n- Priority level (with color code)\n- Due date\n- Current status (Pending, In Progress, Completed)\n- Checklist progress percentage\n\nUse the filter buttons at the top to filter the list:\n- All: All your tasks\n- Active: Pending and in-progress tasks\n- Completed: Finished tasks\n- Overdue: Tasks past their due date (highlighted in red)\n\nTasks are sorted by priority by default. Tap the sort button to sort by due date.' },
 { q: 'How to complete a task?', a: 'The task completion process step by step:\n\n1. Tap a task in the list to open the detail page\n2. Read the task description and instructions\n3. Check off completed checklist items if any\n4. Add comments or notes if needed\n5. If photos are required, use the camera icon to take one or select from gallery\n6. Tap the status field at the top\n7. Select "Completed"\n8. Tap "Confirm" on the confirmation screen\n\nWhen a task is completed, the task owner (creator) receives an automatic notification. Completed tasks appear under the "Completed" filter. The manager can revert the task to "In Progress" if needed.' },
 { q: 'Adding replies and comments to tasks', a: 'A comment area is at the bottom of the task detail page. Use it to share info, ask questions, or report progress.\n\nTo add a comment:\n1. Open the task detail page\n2. Tap the "Add Comment" area\n3. Write your message\n4. Attach a file or photo with the attachment icon if needed\n5. Tap "Send"\n\nComments are displayed chronologically in the task history. All involved parties (task owner and other assignees) receive your comment as a notification. This keeps all task-related communication in one place.' },
 { q: 'Adding photos to tasks', a: 'Adding photos to tasks while in the field is straightforward:\n\n1. Open the task detail page\n2. Tap "Add Photo" or the camera icon\n3. Options appear:\n - Camera: Open your phone camera for an instant photo\n - Gallery: Select an existing photo from your phone\n4. After adding a photo, you can optionally write a description\n5. Tap "Save" to attach the photo to the task\n\nAdded photos are displayed as a gallery in the task detail. Photos are automatically uploaded to the server - if there is no internet, they are stored offline and uploaded automatically when connectivity returns.' },
 ],
 },
 {
 icon: FileText, title: 'Forms & Reports',
 items: [
 { q: 'What is shown in the Forms tab?', a: 'The "Forms" tab shows two types of content:\n\n1. Assigned Reports (top section, orange background):\n- Reports forwarded to you by your manager on the platform\n- Shown with "Report: ..." prefix\n- Displays priority level (Low/Medium/High/Critical) and assigner info\n- Tap to open and take action\n\n2. Form Templates (bottom section):\n- Standard field forms you need to fill out\n- Shows field count and department info\n- Tap to fill out the form\n\nPrioritize assigned reports first - these are tasks expected from you by your manager.' },
 { q: 'How to process an assigned report?', a: 'Tap a "Report: ..." card in the Forms tab. The report detail page opens:\n\n1. Read the report title, description, and priority level\n2. Select a status:\n - Completed: The issue in the report has been resolved\n - Issue Found: A problem was identified regarding the report\n3. Write your field notes in the notes/description area (what you did, what you observed)\n4. Tap "Send"\n\nWhen you submit:\n- Your GPS location is automatically recorded\n- The report owner gets an instant notification\n- OperIQ AI analysis starts automatically\n- Platform users see the report status in real time\n\nYour note appears as "Field Note" in the report detail.' },
 { q: 'How to fill out a form?', a: 'See the forms you need to fill out in the "Forms" tab. Steps:\n\n1. Select the form template from the list\n2. Form fields are displayed - fill each field in order\n3. Field types: text, number, date, single/multi select, photo, location\n4. Required fields are marked with an asterisk (*)\n5. For photo fields, use camera or gallery\n6. For location fields, add your current location automatically\n7. After filling all fields, tap "Send"\n8. Review the info on the confirmation screen and tap "Confirm" to submit\n\nSubmitted forms are sent as notifications to your manager. You can see previously filled forms in the form history.' },
 { q: 'Saving a form as draft', a: 'If you cannot complete a form right away, use the draft save feature:\n\n1. Partially fill out the form\n2. Tap "Save Draft" at the top right\n3. The form appears in "My Drafts"\n4. Later, tap the draft to continue where you left off\n5. Once all fields are complete, tap "Send" to submit\n\nDrafts are stored on your device and server. Draft saving works even without internet. You can edit or delete draft forms.' },
 { q: 'Form history and resubmission', a: 'View previously filled forms in the "Form History" section. History entries show:\n\n- Form name and date\n- Status: Sent, Under Review, Approved, Rejected\n- Submitted data (read-only)\n\nTo fill a form again, tap the "Fill Again" button next to the historical form. Previous answers are pre-filled - update the fields you want to change and resubmit.\n\nFor rejected forms, the rejection reason is shown. Make the necessary corrections and resubmit the form.' },
 { q: 'Adding photos and location to forms', a: 'Some form templates may have required photo and location fields. These fields document your field work.\n\nPhoto Field:\n- Tap the camera icon\n- Use "Take Photo" to open the camera or "Choose from Gallery" to select an existing photo\n- Fields supporting multiple photos have a "+" button for additional photos\n- You can write an optional description for each photo\n\nLocation Field:\n- Tap "Add My Location"\n- Your device captures your current GPS position\n- The location address is displayed automatically\n- You must have granted location permission' },
 ],
 },
 {
 icon: Zap, title: 'OperIQ Mobile Assistant',
 items: [
 { q: 'How do I ask OperIQ a question?', a: 'Tap the OperIQ icon in the bottom menu. The chat screen opens and you can ask the AI assistant questions in natural language.\n\nExample questions for OperIQ:\n- "What are my tasks for today?"\n- "Which tasks are overdue in my department?"\n- "How is the stock status?"\n- "What is the maintenance procedure for this machine?"\n- "Summary of last week\'s reports"\n\nOperIQ answers using your company-specific data. You can ask in Turkish or English. Short, clear questions yield more accurate answers.\n\nYour chat history is saved - scroll to see previous conversations. Use the "New Chat" button to start a fresh conversation.' },
 { q: 'How does photo analysis work?', a: 'Use the visual analysis feature in the OperIQ chat screen to evaluate field conditions with AI:\n\n1. Tap the camera icon in the chat screen\n2. Use "Take Photo" to open your camera or "Choose from Gallery" to select a photo\n3. Describe what you want analyzed (e.g., "Is this machine panel normal?", "Assess this damage")\n4. Tap "Send"\n5. OperIQ analyzes the photo and reports findings as text\n\nPhoto analysis is useful for:\n- Equipment or machine condition assessment\n- Damage or fault detection\n- Safety inspection\n- Stock count verification\n\nThe daily photo analysis limit is 5. The limit resets at midnight.' },
 { q: 'Using voice commands', a: 'You can send voice messages using the microphone icon in the OperIQ chat screen:\n\n1. Tap and hold the microphone icon\n2. Speak your question or command\n3. Release - your speech is converted to text\n4. Review the converted text\n5. Tap "Send" to submit\n\nVoice commands are especially useful when your hands are busy (working in the field, inspecting equipment). Turkish and English speech recognition is supported. Speak clearly in noisy environments.' },
 { q: 'Quick actions with OperIQ', a: 'OperIQ does more than just answer questions - it can also perform actions on your behalf:\n\n- "Create a new task: Check warehouse shelves" - creates a task\n- "Summarize my tasks for today" - provides a task summary\n- "Temperature sensor graph for the last 24 hours" - queries data\n- "List this week\'s reports" - queries reports\n\nOperIQ asks for your confirmation before taking action. For example, for a task creation command, it will ask about priority, assignment, and due date. The action is completed upon your confirmation.\n\nThis feature lets you perform actions quickly without navigating to the platform interface.' },
 ],
 },
 {
 icon: Map, title: 'Location & Sync',
 items: [
 { q: 'How does location sharing work?', a: 'Location sharing in the mobile app works as follows:\n\n1. On first use, the app requests location permission - select "Always Allow"\n2. Once permission is granted, the app sends your location to the platform every 60 seconds\n3. Your location is displayed on the live map in real time\n4. You can see your current location and last update time in your profile\n\nImportant notes about location sharing:\n- Location data is shared only during working hours\n- GPS accuracy is approximately 10-20 meters indoors and 3-5 meters outdoors\n- Optimized to minimize battery consumption\n- You can temporarily pause location sharing from profile settings\n- Your manager can view your location history as a route on the map' },
 { q: 'How does offline mode work?', a: 'When internet connectivity is lost, the mobile app continues working in offline mode:\n\nWhat you can do offline:\n- View the task list (as of the last sync)\n- Update task status\n- Check off checklist items\n- Fill forms and save drafts\n- Add comments and notes\n- Take photos and attach them to tasks\n\nAll these actions are stored locally on your device. When connectivity returns:\n1. The sync button in the top bar blinks orange\n2. Auto-sync starts (or tap the button for manual sync)\n3. All pending data is uploaded to the server\n4. New data from the server is downloaded to your device\n5. The sync button turns green when complete\n\nActions performed offline record date and time based on your device clock.' },
 { q: 'Battery and data usage', a: 'To optimize battery and data usage of the mobile app:\n\nBattery Saving:\n- Location update frequency is automatically optimized\n- Minimal background battery consumption (approximately 3-5% daily)\n- Location update frequency decreases in low battery mode\n\nMobile Data Usage:\n- The app uses approximately 50-100 MB per month (without photos)\n- Photos are preferentially uploaded via WiFi\n- You can enable "Sync on WiFi Only" in settings\n- Zero data usage in offline mode\n\nIf you notice abnormal increases in battery or data usage, close and reopen the app or restart your device.' },
 { q: 'Troubleshooting sync issues', a: 'If you experience sync issues, try these steps:\n\n1. Internet Connection: Ensure WiFi or mobile data is active\n2. Manual Sync: Tap the sync button in the top bar\n3. Restart App: Close the app completely and reopen it\n4. Device Storage: Ensure at least 100 MB of free space on your device\n5. App Update: Clear the browser cache and reload the page\n\nSync status indicators:\n- Green: All data is up to date\n- Orange: Pending data, sync in progress\n- Red: Sync error - try the steps above\n\nIf the issue persists, notify your administrator or technical support.' },
 ],
 },
 {
 icon: Bell, title: 'Mobile Notifications',
 items: [
 { q: 'How do push notifications work?', a: 'Push notifications in the mobile app keep you instantly informed of important events.\n\nYou will receive notifications when:\n- A new task is assigned to you\n- A task status changes\n- A task comment is added\n- A new message arrives\n- A workflow step is waiting for your approval\n- An IoT alarm is triggered (if you have access)\n\nTap a notification to go directly to the relevant page. For example, tapping a task notification opens the task detail page.\n\nIf you are not receiving notifications:\n1. Ensure notification permission is granted in device settings\n2. Make sure "Do Not Disturb" mode is off\n3. Ensure the app is allowed to run in the background' },
 { q: 'Adjusting notification sound and vibration', a: 'Configure notification sound and vibration from your device settings:\n\niPhone:\n1. Settings > Notifications > ActLedger\n2. Configure Sound, Badge, and Banner settings\n3. Choose whether to show on lock screen\n\nAndroid:\n1. Settings > Apps > ActLedger > Notifications\n2. Configure notification categories individually\n3. Set sound, vibration, and priority options\n\nTo avoid being disturbed at night, use your device\'s "Do Not Disturb" scheduling feature. This lets you stop receiving notifications outside working hours.' },
 ],
 },
 {
 icon: Settings, title: 'Profile & Settings',
 items: [
 { q: 'Viewing profile information', a: 'In the "Profile" tab you can see:\n\n- First and Last Name\n- Email address\n- Department and Role\n- Login code (ACT-XXXXXX)\n- Current location (if location sharing is active)\n- Last sync time\n- App version\n\nTo change your profile photo, tap the photo area and select from camera or gallery.' },
 { q: 'Changing your password', a: 'To change your password:\n\n1. Go to the "Profile" tab\n2. Tap "Change Password"\n3. Enter your current password\n4. Enter your new password (at least 8 characters, uppercase, lowercase, number)\n5. Re-enter your new password to confirm\n6. Tap "Save"\n\nA confirmation message appears when the password is successfully changed. Use your new password on next login. Your current session continues.\n\nIf you forget your password, use the "Forgot Password" link on the login screen or request a temporary password from your administrator.' },
 { q: 'Language and notification preferences', a: 'Configure language and notification preferences in profile settings:\n\nLanguage Selection:\n- Choose between Turkish and English\n- Language change applies instantly\n\nNotification Preferences:\n- Task notifications: On/Off\n- Message notifications: On/Off\n- IoT alarm notifications: On/Off\n- System announcements: On/Off\n\nThese settings apply to mobile notifications only. Platform (web) notifications are configured separately from the profile page.' },
 { q: 'How to log out securely', a: 'To log out securely from the app:\n\n1. Go to the "Profile" tab\n2. Tap the "Log Out" button at the bottom of the page\n3. Tap "Yes, Log Out" on the confirmation screen\n\nWhen you log out:\n- Your session is terminated\n- Local data is cleared\n- Location sharing stops\n- You are redirected to the login screen\n\nImportant: If you logged in from a shared or someone else\'s device, always log out when finished. Do not hand over the device without logging out.' },
 ],
 },
]

export { PLATFORM_GUIDE_EN, MOBILE_GUIDE_EN }
