import { useState } from 'react'
import { BookOpen, ChevronDown, ChevronRight, Monitor, Smartphone, Layers, BarChart3, ClipboardList, FileText, Map, MessageSquare, Settings, Users, Package, Cpu, Zap, FolderOpen, Shield, Building2, ArrowRight, Bell, HelpCircle, Rocket, Lock, Workflow } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useLanguage } from '../context/LanguageContext'

interface Section {
  icon: typeof Monitor
  title: string
  path?: string
  items: { q: string; a: string }[]
}

const PLATFORM_GUIDE_TR: Section[] = [
  {
    icon: Rocket, title: 'Hizli Baslangic (Quick Start)',
    items: [
      { q: 'ActLedger nedir ve ne ise yarar?', a: 'ActLedger, isletmenizin tum operasyonel sureclerini tek bir platformda yonetmenizi saglayan kapsamli bir operasyon yonetim sistemidir. Gorev takibi, saha raporlari, KPI olcumu, stok yonetimi, IoT entegrasyonu, canli harita, is akislari ve yapay zeka destekli analiz gibi onlarca modulu bir arada sunar.\n\nPlatforma ilk giris yaptiginizda, yoneticiniz tarafindan size atanan rol ve departmana gore erisim yetkiniz belirlenir. Sol taraftaki ana menuden tum modullere ulasabilirsiniz. Ust barda bildirimler, mesajlar ve profil ayarlarina hizli erisim butonlari bulunur.\n\nBaslamak icin asagidaki adimlari izleyin:\n1. Sol menuden "Kokpit" a tiklayarak dashboard ekranini inceleyin\n2. "Gorevler" bolumune giderek size atanmis gorevleri kontrol edin\n3. Profil sayfanizdan bildirim tercihlerinizi ayarlayin\n4. OperIQ asistanina herhangi bir sorunuzu sormak icin sag alttaki sohbet balonuna tiklayin' },
      { q: 'Ilk giris ve sifre belirleme', a: 'Platformu kullanmaya baslamak icin yoneticinizin size verdigi e-posta adresi ve gecici sifre ile giris yapin. Giris ekraninda "E-posta" ve "Sifre" alanlarini doldurun, ardindan "Giris Yap" butonuna basin.\n\nIlk giriste sistem sizden sifrenizi degistirmenizi isteyecektir. Yeni sifreniz en az 8 karakter uzunlugunda olmali ve buyuk harf, kucuk harf, rakam ve ozel karakter icermelidir. Sifrenizi belirledikten sonra tekrar giris yaparak platforma erisebilirsiniz.\n\nSifrenizi unutursaniz giris ekranindaki "Sifremi Unuttum" linkine tiklayarak e-posta adresinize sifirlama baglantisi gonderebilirsiniz. Bu baglanti 24 saat gecerlidir.' },
      { q: 'Sol menu ve navigasyon yapisi', a: 'Platformun sol tarafinda ana navigasyon menusu bulunur. Bu menu uzerinden tum modullere erisebilirsiniz. Menudeki ana basliklar sunlardir:\n\n- Kokpit: Ana dashboard ve ozet gorunumler\n- Gorevler: Gorev olusturma, takip ve yonetim\n- Raporlar: Saha raporlari ve analizler\n- KPI Panel: Performans gostergeleri ve hedefler\n- Kullanicilar: Personel ve departman yonetimi\n- Canli Harita: Konum takibi ve tesis haritalari\n- IoT Cihazlar: Sensor ve cihaz izleme\n- Stok: Envanter ve malzeme yonetimi\n- Dosyalar: Dokuman ve dosya paylasimi\n- Otomasyon: Is akislari ve otomatik kurallar\n- Mesajlar: Dahili iletisim sistemi\n\nMenuyu daraltmak icin sol ustteki hamburger ikonuna tiklayabilirsiniz. Bu sayede calisma alaniniz genisler. Tekrar tiklayarak menuyu acabilirsiniz.' },
      { q: 'OperIQ yapay zeka asistani nedir?', a: 'OperIQ, ActLedger platformunun icine entegre edilmis yapay zeka asistanidir. Platformun her yerinde size yardimci olur. Sag alt kosedeki sohbet balonuna tiklayarak OperIQ ile konusmaya baslayabilirsiniz.\n\nOperIQ su konularda size yardimci olabilir:\n- Gorevleriniz hakkinda sorular sorma ve ozet alma\n- Raporlari otomatik analiz etme ve bulgulari ozetleme\n- Grafik ve gorsellestirme olusturma\n- Stok durumu hakkinda bilgi alma\n- KPI performansinizi yorumlama\n- Teknik sorulariniza cevap verme\n\nOperIQ, sirketinize ozel verileri kullanarak baglama uygun cevaplar uretir. Dogal dilde (Turkce veya Ingilizce) soru sorabilirsiniz. Ornegin "Bu ayin en cok geciken gorevleri hangileri?" veya "Uretim hattindaki sicaklik sensoru son 24 saatte nasil degisti?" gibi sorular sorabilirsiniz.' },
      { q: 'Dil ve tema ayarlari', a: 'ActLedger Turkce ve Ingilizce dillerini destekler. Dili degistirmek icin sag ust kosedeki profil ikonunuza tiklayin ve dil seceneklerinden istediginizi secin. Dil degisikligi aninda uygulanir ve sayfa yenilenmesine gerek kalmaz.\n\nPlatform acik (light) tema ile calisir. Tum sayfalar tutarli ve okunabilir bir tasarimla sunulur. Tarayicinizin yakinlastirma (zoom) ozelligini kullanarak metin boyutunu ihtiyaciniza gore ayarlayabilirsiniz (Ctrl + veya Ctrl - kisayollari ile).' },
    ],
  },
  {
    icon: Monitor, title: 'Kokpit & Dashboard', path: '/panel',
    items: [
      { q: 'Dashboard nasil kullanilir?', a: 'Sol menuden "Kokpit" a tiklayarak ana dashboard ekranina ulasin. Dashboard, isletmenizin genel durumunu tek bakista gormenizi saglayan ozet ekranidir. Burada gorev istatistikleri, KPI ozeti, son raporlar, bildirimler ve departman bazinda performans gostergeleri yer alir.\n\nSuruklenebilir widgetlar ile kendi gorunumunuzu olusturabilirsiniz. Her widget bir veri kaynagini gorsellestirir - pasta grafik, cubuk grafik, sayi karti, liste veya harita seklinde olabilir. Sag ustteki "+" butonu ile yeni widget ekleyebilir, widgetlari surukleyerek siralayabilirsiniz.\n\nDashboard verileri varsayilan olarak canli guncellenir. Sag ustteki yenileme butonuyla verileri manuel olarak da guncelleyebilirsiniz. Tarih araligini degistirerek farkli zaman dilimlerindeki verileri gorebilirsiniz.' },
      { q: 'Yeni dashboard nasil eklenir?', a: 'Dashboard basliginin yanindaki dropdown\'dan "Yeni Dashboard" secin. Asagidaki adimlari izleyin:\n\n1. Dashboard\'a bir ad verin (orn: "Haftalik Uretim Ozeti" veya "Saha Performansi")\n2. Widget ekle butonuna tiklayin ve istediginiz widget tipini secin\n3. Her widget icin veri kaynagi, gorsellestirme tipi ve filtreleri ayarlayin\n4. Widgetlari surukleyerek istediginiz duzenle yerlestirin\n5. "Kaydet" butonuna basarak dashboard\'unuzu kaydedin\n\nBirden fazla dashboard olusturabilir ve aralarinda hizlica gecis yapabilirsiniz. Ornegin bir dashboard gunluk operasyonlar icin, baskasi haftalik yonetim toplantilari icin olabilir. Dashboard\'lari diger kullanicilarla da paylasabilirsiniz.' },
      { q: 'OperIQ ile grafik nasil olusturulur?', a: '"Veri Gorsellestirme" butonuna tiklayin. Acilan pencerede dogal dilde ne gormek istediginizi yazin. OperIQ otomatik olarak en uygun grafik tipini secer ve yapilandirir.\n\nOrnek komutlar:\n- "Departmanlara gore gorev dagilimi" - pasta grafik olusturur\n- "Son 30 gundeki rapor sayisi" - cizgi grafik olusturur\n- "En yuksek KPI performansina sahip 10 departman" - cubuk grafik olusturur\n- "Stok seviyesi kritik olan urunler" - tablo goruntusunde listeler\n\nOlusturulan grafigi dashboard\'unuza widget olarak ekleyebilir, PNG veya PDF formatinda indirebilir ya da dogrudan rapor icerisinde kullanabilirsiniz. OperIQ ayrica veriler hakkinda otomatik yorum ve oneriler de sunar.' },
      { q: 'Widget tipleri ve ozellikleri', a: 'Dashboard\'da kullanabileceginiz widget tipleri sunlardir:\n\n- Sayi Karti: Tek bir metrik degerini buyuk rakamlara ile gosterir (orn: toplam acik gorev sayisi, bugunun rapor sayisi)\n- Pasta Grafik: Dagilim verilerini oransal olarak gosterir (orn: gorev durumlarina gore dagilim)\n- Cubuk Grafik: Karsilastirmali verileri yan yana gosterir (orn: departman bazinda performans)\n- Cizgi Grafik: Zaman icerisindeki degisimi izler (orn: haftalik gorev tamamlanma trendi)\n- Tablo: Detayli veri listesini satirlar halinde gosterir (orn: geciken gorevler listesi)\n- Harita: Konum bazli verileri harita uzerinde gosterir (orn: saha ekiplerinin konumlari)\n\nHer widget uzerinde fareyi gezdirdiginizde sag ust kosede duzenle, boyutlandir ve sil butonlari gorunur. Widget ayarlarindan veri kaynagini, renkleri ve yenileme sikligini degistirebilirsiniz.' },
      { q: 'Dashboard filtreleme ve tarih araligi', a: 'Dashboard\'un ust kismindaki filtre cubugunu kullanarak gorunen verileri daraltabilirsiniz. Kullanabileceginiz filtreler:\n\n- Tarih Araligi: Bugun, bu hafta, bu ay, son 30 gun veya ozel tarih araligi secebilirsiniz\n- Departman: Belirli bir departmanin verilerini gormek icin secim yapin\n- Kullanici: Belirli bir kullaniciya ait verileri filtrelemek icin secin\n- Durum: Gorev veya rapor durumuna gore filtreleyin\n\nFiltreler tum widgetlara ayni anda uygulanir. Filtreleri temizlemek icin "Filtreleri Sifirla" butonuna basin. Sik kullandiginiz filtre kombinasyonlarini kayitli gorunum olarak saklayabilirsiniz.' },
    ],
  },
  {
    icon: ClipboardList, title: 'Gorev Yonetimi', path: '/gorevler',
    items: [
      { q: 'Yeni gorev nasil olusturulur?', a: 'Sol menuden "Gorevler"e gidin, sag ustteki "Yeni Gorev" butonuna basin. Gorev olusturma formu acilacaktir. Asagidaki adimlari izleyin:\n\n1. Baslik: Gorevi kisa ve net bir sekilde tanimlayan bir baslik girin\n2. Aciklama: Gorevin detaylarini, beklenen ciktilari ve onemli notlari yazin\n3. Departman: Gorevin ait oldugu departmani secin\n4. Atanan Kisi: Gorevi yapacak personeli secin (birden fazla kisi atayabilirsiniz)\n5. Oncelik: Dusuk, Normal, Yuksek veya Kritik oncelik seviyesini belirleyin\n6. Teslim Tarihi: Gorevin tamamlanmasi gereken son tarihi secin\n7. Etiketler: Gorevi kategorize etmek icin etiketler ekleyin\n\nGorev olusturduktan sonra atanan kisiye otomatik bildirim gonderilir. Gorev kartinda tum detaylar gorunur ve ilerleme durumu takip edilebilir.' },
      { q: 'Gorev durumu nasil guncellenir?', a: 'Gorev kartina tiklayarak detay penceresini acin. Durum alani sag ustte yer alir ve su secenekleri icerir:\n\n- Beklemede: Gorev henuz baslanmamis, atanmis durumda\n- Devam Ediyor: Gorev uzerinde aktif olarak calisiliyor\n- Incelemede: Gorev tamamlanmis ve yoneticinin onayini bekliyor\n- Tamamlandi: Gorev basariyla tamamlanmis\n- Iptal Edildi: Gorev iptal edilmis\n\nDurum degisikligi yapildiginda sistem otomatik olarak zaman damgasi kaydeder ve ilgili kisilere bildirim gonderir. Gorev gecmisinde tum durum degisiklikleri tarih ve saat bilgisiyle birlikte goruntulenir.\n\nGorev uzerinde yorum da birakabilirsiniz. Yorum alanina yazin ve "Gonder" butonuna basin. Yorumlar tum ilgili kisilere bildirim olarak iletilir.' },
      { q: 'Checklist nasil eklenir?', a: 'Gorev detayinda "Checklist" bolumune gidin ve yeni maddeler ekleyin. Checklist, bir gorevi alt adimlara bolmenize olanak tanir ve ilerlemenin gorsel olarak takip edilmesini saglar.\n\nChecklist kullanmak icin:\n1. Gorev detay sayfasini acin\n2. "Checklist" bolumunde "Yeni Madde Ekle" butonuna basin\n3. Madde metnini yazin ve Enter\'a basin\n4. Birden fazla madde ekleyerek gorev adimlarini tanimlayin\n5. Her tamamlanan adimi isaretleyin - ilerleme cubugu otomatik guncellenir\n\nChecklist ilerlemesi yuzde olarak gorev kartinda da gorunur. Ornegin 8 maddeden 4\'u tamamlanmissa "%50" seklinde gosterilir. Bu sayede gorevlerin ne asama da oldugunu listeden bile gorebilirsiniz.' },
      { q: 'Gorev filtreleme ve arama', a: 'Gorev listesinin ustundeki filtre cubugu ile gorevleri cesitli kriterlere gore filtreleyebilirsiniz:\n\n- Durum Filtresi: Beklemede, Devam Ediyor, Tamamlandi gibi durumlara gore filtreleyin\n- Oncelik Filtresi: Kritik, Yuksek, Normal, Dusuk onceliklere gore siralayin\n- Departman Filtresi: Belirli departmanlara ait gorevleri gorun\n- Tarih Filtresi: Belirli tarih araligindaki gorevleri listeleyin\n- Atanan Kisi: Belirli bir kisiye atanmis gorevleri bulun\n\nArama cubuguna gorev basligi veya aciklamasindaki anahtar kelimeleri yazarak hizli arama yapabilirsiniz. Filtreler birlikte kullanilabilir - ornegin "Kritik oncelikli ve geciken gorevler" gibi kombinasyonlar olusturabilirsiniz.' },
      { q: 'Gorev takvimi ve zaman cizelgesi', a: 'Gorev listesinin ust kismindaki gorunum seceneklerinden "Takvim" gorunumune gecebilirsiniz. Takvim gorunumunde gorevler teslim tarihlerine gore takvim uzerinde gosterilir.\n\nFarkli gorunum secenekleri sunlardir:\n- Liste Gorunumu: Gorevleri satirlar halinde listeler, en cok detay bu gorunumde gorulur\n- Kanban Gorunumu: Gorevleri durum sutunlarinda kartlar halinde gosterir, surukle-birak ile durum degistirebilirsiniz\n- Takvim Gorunumu: Gorevleri takvim uzerinde tarihlere gore yerlestirir\n\nKanban gorunumunde gorev kartini bir sutundan digerine surukleyerek durum degisikligi yapabilirsiniz. Ornegin "Beklemede" sutunundan "Devam Ediyor" sutununa suruklemek gorevin durumunu otomatik gunceller.' },
      { q: 'Gorev yanit sistemi nasil calisir?', a: 'Gorevlere atanan kisiler gorev uzerinden dogrudan yanit verebilir. Yanit sistemi ile gorevin ilerleyisi hakkinda bilgi paylasabilir, soru sorabilir veya sorun bildirebilirsiniz.\n\nYanit vermek icin:\n1. Gorev detay sayfasini acin\n2. Alt kisimda yer alan "Yanit / Yorum" bolumune gidin\n3. Mesajinizi yazin, gerekirse dosya veya fotograf ekleyin\n4. "Gonder" butonuna basin\n\nYanitlar kronolojik siraya ile listelenir ve tum ilgili kisilere bildirim gonderilir. Yonetici, gorev uzerindeki yanitlari inceleyerek gerekirse talimat verebilir veya gorevi yeniden atayabilir. Bu sistem, gorev hakkindaki tum iletisimi tek bir yerde toplayarak bilgi kayiplarini onler.' },
    ],
  },
  {
    icon: FileText, title: 'Saha Raporlari', path: '/raporlar',
    items: [
      { q: 'Rapor nasil olusturulur?', a: 'Sol menuden "Raporlar"a gidin ve "Yeni Rapor" butonuna basin. Rapor olusturma formunu adim adim doldurun:\n\n1. Baslik: Rapor konusunu ozetleyen net bir baslik girin\n2. Aciklama: Durumu detayli bir sekilde anlatın - ne oldu, nerede oldu, ne zaman fark edildi\n3. Departman: Raporun ilgili oldugu departmani secin\n4. Siddet Derecesi: Dusuk, Orta, Yuksek veya Kritik olarak belirleyin\n5. Konum: Raporun ilgili oldugu fiziksel konumu isaretleyin\n6. Fotograflar: Durumu belgeleyen fotograflari yukleyin (birden fazla fotograf ekleyebilirsiniz)\n7. Ilgili Gorev: Varsa raporla iliskili gorevi baglayin\n\nRapor gonderildikten sonra ilgili departman yoneticisine otomatik bildirim gider. Kritik raporlar aninda tum ust yonetime iletilir.' },
      { q: 'OperIQ rapor analizi nasil calisir?', a: 'Rapor olusturuldugunda OperIQ otomatik olarak icerigini analiz eder. Bu analiz birden fazla katmanda gerceklesir:\n\n- Metin Analizi: Raporun aciklama kismini inceleyerek anahtar bulgu ve temalari cikarir\n- Fotograf Analizi: Yuklenen gorselleri inceleyerek gorsel bulgulari tespit eder\n- Gecmis Karsilastirma: Benzer gecmis raporlarla karsilastirma yaparak tekrarlayan kaliplari belirler\n- Risk Degerlendirmesi: Raporun potansiyel etkisini ve aciliyet seviyesini degerlendirir\n\nAnaliz sonuclari rapor detay sayfasinda "OperIQ Analizi" bolumunde goruntulenir. Burada onerilen aksiyonlar, olasi nedenler ve risk puani yer alir. OperIQ tarafindan onerilen aksiyonlari tek tikla goreve donusturebilirsiniz.' },
      { q: 'Rapor durumlarini takip etme', a: 'Her raporun bir yasam dongusu vardir ve durumu adim adim ilerler:\n\n- Olusturuldu: Rapor yeni gonderilmis, henuz incelenmemis\n- Inceleniyor: Yetkili kisi raporu incelemeye almis\n- Aksiyonda: Rapor icin aksiyon plani olusturulmus ve uygulanıyor\n- Cozuldu: Rapordaki sorun giderilmis\n- Kapatildi: Rapor tamamlanmis ve arsivlenmis\n\nRapor listesinde her raporun guncel durumu renk kodlariyla gosterilir. Raporlarinizin durumunu takip etmek icin "Raporlarim" filtresini kullanabilirsiniz. Rapor durumu her degistiginde size bildirim gonderilir.' },
      { q: 'Rapor filtreleme ve gecmis arama', a: 'Rapor listesini filtrelemek icin ust kisimdaki filtre araclarina kullabilirsiniz:\n\n- Tarih Araligi: Belirli bir zaman dilimindeki raporlari gorun\n- Departman: Belirli departmanlara ait raporlari listeleyin\n- Siddet Derecesi: Kritik, yuksek, orta veya dusuk siddet filtresi\n- Durum: Olusturuldu, inceleniyor, cozuldu gibi durumlara gore filtreleyin\n- Arama: Rapor basligi veya icerigi icerisinde anahtar kelime arayin\n\nRaporlari Excel formatinda disa aktarabilirsiniz. Bu sayede detayli analiz veya yonetim sunumu icin rapor verilerini kullanabilirsiniz.' },
      { q: 'Raporlara dosya ve fotograf ekleme', a: 'Rapor olusturma veya duzenleme ekraninda dosya ve fotograf ekleme bolumu bulunur.\n\nFotograf eklemek icin:\n- "Fotograf Ekle" butonuna basin\n- Bilgisayarinizdan dosya secin veya surukleyip birakin\n- Birden fazla fotograf ekleyebilirsiniz\n- Desteklenen formatlar: JPG, PNG, GIF, WebP\n- Maksimum dosya boyutu: 10 MB\n\nDosya eklemek icin:\n- "Dosya Ekle" butonuna basin\n- PDF, Word, Excel veya metin dosyasi secin\n- Dosyalar rapor detayinda goruntulenir ve indirilebilir\n\nYuklenen fotograflar rapor detayinda galeri gorunumunde goruntulenir. Fotograflara tiklayarak buyutebilir ve aralarinda gezinebilirsiniz.' },
    ],
  },
  {
    icon: BarChart3, title: 'KPI Yonetimi', path: '/kpi-panel',
    items: [
      { q: 'KPI nasil tanimlanir?', a: 'Sol menuden "KPI Panel"e gidin. Sektor sablonundan hazir KPI\'lar zaten yuklenmistir. Yeni KPI eklemek veya mevcut KPI\'lari duzenlemek icin asagidaki adimlari izleyin:\n\n1. "KPI Ekle" butonuna basin\n2. KPI adini ve aciklamasini girin\n3. Olcum birimini secin (yuzde, sayi, sure, tutar vb.)\n4. Hedef degerini belirleyin\n5. Olcum sikligini secin (gunluk, haftalik, aylik, ceyreklik)\n6. Ilgili departmani atayın\n7. KPI katmanini secin (stratejik, taktik, operasyonel, bireysel veya AI)\n\nKPI tanimlandiktan sonra ilgili departman ve kullanicilar bu KPI degerini duzenli olarak girebilir. Gerceklesen degerler hedefe kiyasla otomatik olarak performans yuzdesi hesaplanir.' },
      { q: 'KPI katmanlari nedir?', a: 'ActLedger 5 katmanli KPI yapisi sunar. Her katman farkli yonetim seviyesine hitap eder:\n\n1. Stratejik KPI\'lar (Ust Yonetim): Sirketin genel performansini olcer. Ornek: yillik gelir buyumesi, musteri memnuniyeti endeksi, pazar payi\n2. Taktik KPI\'lar (Orta Yonetim): Departman hedeflerini olcer. Ornek: departman bazinda verimlilik, proje tamamlanma orani\n3. Operasyonel KPI\'lar (Saha): Gunluk operasyonlarin etkinligini olcer. Ornek: gunluk uretim miktari, ariza cozum suresi\n4. Bireysel KPI\'lar (Kisisel): Her calisanin bireysel performansini olcer. Ornek: gorev tamamlama orani, cevap suresi\n5. AI KPI\'lar (OperIQ Uretimi): OperIQ tarafindan verilerden otomatik turetilen metrikler. Ornek: trend analizi, anomali tespiti, tahminleme skorlari\n\nKPI panelinde katman bazinda filtreleme yaparak sadece ilgilendiginiz seviyedeki KPI\'lari gorebilirsiniz.' },
      { q: 'KPI gerceklesen deger girisi nasil yapilir?', a: 'KPI deger girisi icin iki yontem mevcuttur:\n\nManuel Giris:\n1. KPI Panel sayfasinda ilgili KPI\'yi bulun\n2. "Deger Gir" butonuna tiklayin\n3. Gerceklesen degeri girin ve tarih bilgisini secin\n4. Gerekirse not veya aciklama ekleyin\n5. "Kaydet" butonuna basin\n\nToplu Giris (Excel):\n1. KPI Panel sayfasinda "Toplu Giris" butonuna basin\n2. Sablon Excel dosyasini indirin\n3. Degerleri Excel\'de doldurun\n4. Dosyayi yukleyin ve onizlemede kontrol edin\n5. "Kaydet" ile tum degerleri kaydedin\n\nDuzenli veri girisi yapilmayan KPI\'lar icin sistem uyari olusturur ve ilgili departman yoneticisine hatirlatma gonderir.' },
      { q: 'KPI performans goruntuleme ve raporlama', a: 'KPI panelinde her KPI icin gorsel performans gostergeleri bulunur:\n\n- Yesilden kirmiziya renk skalasi hedefe yakinligi gosterir\n- Trend oklari yukselis veya dusus yonunu belirtir\n- Grafik gorunumde zaman icerisindeki degisim izlenebilir\n\nDetayli KPI raporlari icin:\n- KPI adina tiklayarak detay sayfasini acin\n- Gecmis verileri grafik uzerinde inceleyin\n- Departman veya kisi bazinda karsilastirma yapin\n- OperIQ analizi ile trend tahminlerini gorun\n\nKPI verilerini PDF veya Excel formatinda disari aktarabilirsiniz. Aylik KPI ozet raporlari otomatik olarak olusturulur ve yonetim ekibine gonderilir.' },
      { q: 'Sektor sablonlari ve hazir KPI setleri', a: 'ActLedger, 15 farkli sektor icin hazir KPI sablonlari sunar. Sirketiniz olusturulurken sektorunuze uygun sablon otomatik olarak yuklenir. Bu sablonlar binlerce KPI iceren kapsamli kutuphanelerdir.\n\nHer sektor sablonunda:\n- Departman bazinda gruplanmis KPI\'lar\n- Olcum birimleri ve hedef araliklari on-tanimli olarak gelir\n- Sektore ozgu metrikler ve terminoloji kullanilir\n\nSablon KPI\'larini ihtiyaclariniza gore duzenleyebilirsiniz: hedef degerlerini degistirin, gereksiz KPI\'lari devre disi birakin veya yenilerini ekleyin. Sablona ek olarak kendi ozel KPI\'larinizi da tanimlayabilirsiniz.' },
    ],
  },
  {
    icon: Users, title: 'Kullanici & Departman Yonetimi', path: '/kullanicilar',
    items: [
      { q: 'Yeni kullanici nasil eklenir?', a: '"Kullanicilar" sayfasindan "Yeni Kullanici" butonuna basin. Kullanici olusturma formunu doldurun:\n\n1. Ad ve Soyad: Kullanicinin tam adini girin\n2. E-posta: Giris icin kullanilacak e-posta adresini girin\n3. Telefon: Iletisim icin telefon numarasini girin\n4. Rol: 8 rol seviyesinden birini secin (asagida detayli aciklama var)\n5. Departman: Kullanicinin bagli oldugu departmani secin\n6. Giris Kodu: Sistem otomatik olarak ACT-XXXXXX formatinda bir giris kodu uretir\n\nKullanici olusturulunca gecici sifre ile birlikte giris bilgileri e-posta ile iletilir. Kullanici ilk girisinde sifresini degistirmek zorundadir. Toplu kullanici eklemek icin Excel sablonunu kullanabilirsiniz.' },
      { q: 'Rol seviyeleri nedir?', a: '8 seviyeli yetki sistemi hiyerarsik olarak calisir. Her seviye bir ust seviyenin tum yetkilerini icerir:\n\n1. Isci (Seviye 1): Kendisine atanan gorevleri gorebilir ve tamamlayabilir, form doldurabilir\n2. Teknisyen (Seviye 2): Isci yetkilerine ek olarak rapor olusturabilir ve IoT verilerini gorebilir\n3. Usta (Seviye 3): Gorev olusturabilir ve kendi ekibine atayabilir\n4. Supervizor (Seviye 4): Departmanindaki tum gorev ve raporlari gorebilir, stok hareketi yapabilir\n5. Sef (Seviye 5): Departman KPI\'larini yonetebilir, is akisi olusturabilir\n6. Mudur (Seviye 6): Birden fazla departmani yonetebilir, kullanici ekleyebilir\n7. Direktor (Seviye 7): Tum departmanlari gorebilir, otomasyon kurallari olusturabilir\n8. Genel Mudur (Seviye 8): Tam yetki - tum modullere ve ayarlara erisim\n\nRol atamasi yapilirken dikkatli olun. Bir kullanicinin rolunu daha sonra degistirebilirsiniz.' },
      { q: 'Departman nasil olusturulur ve yonetilir?', a: 'Departman yonetimi icin "Kullanicilar" sayfasindaki "Departmanlar" sekmesine gecin. Yeni departman olusturmak icin:\n\n1. "Yeni Departman" butonuna basin\n2. Departman adini girin\n3. Ust departmani secin (varsa - hiyerarsik yapi icin)\n4. Departman yoneticisini atayın\n5. Varsayilan KPI setini secin\n6. "Kaydet" butonuna basin\n\nDepartman hiyerarsisi agac yapisinda goruntulenir. Her departmanin altinda alt departmanlar olusturabilirsiniz. Ornegin "Uretim" departmaninin altinda "Montaj", "Kalite Kontrol", "Paketleme" gibi alt departmanlar tanimlayabilirsiniz.\n\nDepartman yoneticisi degistirildginde tum atamalar ve yetkiler otomatik olarak guncellenir.' },
      { q: 'Kullanici profilini duzenleme', a: 'Bir kullanicinin profilini duzenlemek icin kullanici listesinde ismine tiklayin. Profil sayfasinda su alanlari guncelleyebilirsiniz:\n\n- Kisisel Bilgiler: Ad, soyad, telefon, e-posta\n- Rol ve Departman: Yetki seviyesi ve bagli departman\n- Profil Fotografi: Kullanicinin fotografi\n- Bildirim Tercihleri: Hangi bildirimleri alacagini ayarlama\n- Sifre Sifirlama: Kullanicinin sifresini sifirlayabilirsiniz\n\nKullanicilari devre disi birakabilirsiniz (silmek yerine). Devre disi birakilan kullanici giris yapamaz ancak gecmis kayitlari korunur. Bunu "Hesabi Devre Disi Birak" butonu ile yapabilirsiniz.' },
      { q: 'Toplu kullanici ekleme (Excel)', a: 'Cok sayida kullanici eklemek icin Excel sablon yuklemesini kullanin:\n\n1. "Kullanicilar" sayfasinda "Toplu Ekle" butonuna basin\n2. "Sablon Indir" ile bos Excel sablonunu indirin\n3. Sablondaki sutunlari doldurun: Ad, Soyad, E-posta, Telefon, Departman, Rol\n4. Doldurulmus dosyayi yukleyin\n5. Onizleme ekraninda verileri kontrol edin - hatali satirlar kirmizi ile isaretlenir\n6. "Kullanicilari Olustur" butonuyla tum kullanicilari tek seferde ekleyin\n\nHer kullaniciya otomatik giris kodu ve gecici sifre uretilir. Giris bilgilerini iceren bir ozet dosyasi indirebilirsiniz. Bu dosyayi ilgili kisilere guvenli bir sekilde iletin.' },
    ],
  },
  {
    icon: Map, title: 'Canli Harita', path: '/harita',
    items: [
      { q: 'Personel konumlari nasil goruntulenir?', a: '"Canli Harita" sayfasinda aktif konum paylasan personelleri harita uzerinde gorun. Her personel bir isaretci (pin) ile gosterilir ve ustune tiklayinca ad, departman ve son konum guncelleme zamani goruntulenir.\n\nHarita uzerindeki filtreleme secenekleri:\n- Departman Filtresi: Belirli departmanlardaki personeli gorun\n- Durum Filtresi: Aktif, molada veya cevrimdisi personeli filtreleyin\n- Zaman Filtresi: Son 1 saat, 4 saat veya 24 saat icerisindeki konumlari gorun\n\nPersonel konumlari varsayilan olarak 60 saniyede bir guncellenir. Harita uzerinde yakinlastirip uzaklastirarak farkli detay seviyelerinde gorebilirsiniz. Belirli bir bolgeye odaklanmak icin haritayi surukleyin veya arama cubugundan adres arayin.' },
      { q: 'Tesis nasil isaretlenir?', a: 'Harita uzerinde tesis, fabrika, depo veya ofis konumlarini isaretleyebilirsiniz:\n\n1. Harita uzerinde istediginiz konuma sag tiklayin\n2. "Yeni Tesis Ekle" secenegini secin\n3. Tesis adini ve tipini girin (Fabrika, Ofis, Depo, Santiye vb.)\n4. Adresi yazip onaylayin veya haritadaki konumu kullanin\n5. Koordinat formatini secin: DMS (derece-dakika-saniye) veya decimal\n6. "Kaydet" butonuna basin\n\nTesisler harita uzerinde ozel ikonlarla gosterilir. Tesis ikonuna tiklayinca tesis bilgileri, aktif personel sayisi ve ilgili gorevler goruntulenir. Tesis bilgilerini daha sonra duzenleyebilir veya silebilirsiniz.' },
      { q: 'Rota ve hareket gecmisi', a: 'Bir personelin gun icerisindeki hareketlerini harita uzerinde rota olarak gorebilirsiniz:\n\n1. Haritada personel isaretcisine tiklayin\n2. "Rota Gecmisi" butonuna basin\n3. Tarih araligini secin\n4. Personelin hareketleri harita uzerinde cizgi olarak gosterilir\n\nRota gecmisi, saha ekiplerinin verimliligini analiz etmek ve ziyaret edilen noktalari dogrulamak icin kullanislidir. Her durak noktasinda kalinan sure goruntulenir.' },
      { q: 'Harita gorunum secenekleri', a: 'Harita farkli gorunum modlarini destekler:\n\n- Standart Harita: Klasik sokak haritasi gorunumu\n- Uydu Gorunumu: Uydu fotograflari ile gercekci gorunum\n- Arazi Gorunumu: Topografik detaylari iceren gorunum\n- Isı Haritasi: Personel yogunlugunu isi haritasi olarak gosterir\n\nGorunum degistirmek icin haritanin sag ust kosesindeki katman butonuna tiklayin. Harita uzerinde olcum araci ile iki nokta arasindaki mesafeyi olcebilirsiniz. Haritayi tam ekran modunda acmak icin genisletme butonunu kullanin.' },
    ],
  },
  {
    icon: Building2, title: 'Tesis Haritasi (Live Facility Map)', path: '/harita',
    items: [
      { q: 'Tesis plani nasil yuklenir?', a: '"Canli Operasyon & Tesis Haritalari" sayfasinda "Tesis Haritasi" sekmesine gecin. Tesis plani yuklemek icin asagidaki adimlari izleyin:\n\n1. "Plan Yukle" butonuna tiklayin\n2. Dosya seciniz - desteklenen formatlar: PNG, JPG, SVG\n3. Plan adi ve kat bilgisini girin (orn: "Ana Fabrika - Zemin Kat")\n4. Plani yukleyin ve boyutlandirma ayarlarini yapin\n5. "Kaydet" ile plani onaylayin\n\nBirden fazla kat plani yukleyebilirsiniz. Katlar arasinda gecis yapmak icin ust kisimda yer alan kat secici butonlarini kullanin. Plan yukledikten sonra uzerine alanlar ve isaretciler ekleyerek canli bir tesis haritasi olusturabilirsiniz.\n\nEn iyi sonuc icin yuksek cozunurluklu ve net bir plan gorseli kullanmanizi oneririz. SVG formati yakinlastirma sirasinda en iyi kaliteyi sunar.' },
      { q: 'Alan ve isaretci nasil eklenir?', a: '"Duzenle" modunu aktif edip plan uzerine tiklayarak alan veya isaretci ekleyin. Alan ekleme adimlari:\n\n1. "Duzenle" butonuna basin - plan duzenleme moduna gecer\n2. Plan uzerinde istediginiz noktaya tiklayin\n3. Acilan formda alan bilgilerini doldurun:\n   - Tip: Departman, Makine, Depo, Ofis, Ortak Alan, Tehlike Bolgesi vb.\n   - Katman: Departmanlar, IoT, Gorevler, Stok, Acil Durum\n   - Renk ve boyut ayarlari\n   - Iliskili oge: Departman, IoT cihaz veya stok kalemi ile baglanti\n4. "Kaydet" ile alani onaylayin\n\nOlusturulan alanlar plan uzerinde renk kodlariyla goruntulenir. Her alana tiklayarak detay bilgilerini gorebilir, canli verileri izleyebilir ve hizli islemler yapabilirsiniz.' },
      { q: 'Katmanlar nasil acilir/kapatilir?', a: 'Haritanin ustundeki katman butonlariyla farkli veri katmanlarini kontrol edebilirsiniz. Mevcut katmanlar:\n\n- Departmanlar: Departman alanlarini ve personel yogunlugunu gosterir\n- IoT: Sensor ve cihaz konumlarini ve canli degerlerini gosterir\n- Gorevler: Aktif gorevlerin konumlarini gosterir\n- Stok: Stok kalemlerinin depolama konumlarini gosterir\n- Acil Durum: Acil cikislar, yangin sondurucular ve tehlike bolgelerini gosterir\n\nHer katmani bagimsiz olarak acip kapatabilirsiniz. Birden fazla katmani ayni anda goruntulemek mumkundur. Katman secimi tesis haritasinin ustundeki toggle butonlari ile yapilir.' },
      { q: 'Sektor sablonu nasil uygulanir?', a: '"Sablon" butonuyla sektorunuze uygun hazir alan yerlesimini secin. Mevcut sablon kategorileri:\n\n- Uretim: Uretim hatlari, kalite kontrol, hammadde deposu, sevkiyat alani\n- Lojistik: Yuk alani, arac parki, soforler odasi, dagitim merkezi\n- Saglik: Hasta kabul, ameliyathane, eczane, laboratuvar\n- Perakende: Satis alani, depo, kasa bolumu, muduriyet\n- Enerji: Kontrol odasi, trafo, generator, bakım atölyesi\n- Egitim: Siniflar, laboratuvar, kutuphane, yemekhane\n\nSablon uyguladiginda mevcut alanlara dokunulmaz, yeni alanlar eklenir. Sablon alanlarini daha sonra istediginiz gibi duzenleyebilir, tasiyabilir veya silebilirsiniz.' },
      { q: 'Canli veri nasil goruntulenir?', a: 'IoT cihazlarina, departmanlara veya stok kalemlerine baglanan alanlarda canli durum rozetleri gorursunuz. Renk kodlari:\n\n- Yesil: Normal - tum degerler kabul edilebilir aralikta\n- Sari: Uyari - bazi degerler uyari esigine yaklasti\n- Kirmizi: Kritik - degerler kritik esigi asti, acil mudahale gerekli\n- Gri: Baglanti yok - cihaz cevrimdisi veya veri gelmiyor\n\nBir alana tiklayinca detay penceresi acilir ve su bilgiler goruntulenir:\n- Canli sensor degerleri (sicaklik, nem, basinc vb.)\n- Son 24 saatlik trend grafigi\n- Aktif alarm ve uyarilar\n- O alandaki personel listesi\n- Iliskili gorevler ve raporlar' },
      { q: 'Acil durum modu nedir?', a: '"Acil Durum" butonuyla tesis haritasi acil durum moduna gecer. Bu modda:\n\n- Tehlike bolgeleri kirmizi parlak sinirlarlsa vurgulanir\n- Acil cikis noktalari yesil yanip sonen ikonlarla isaretlenir\n- Yangin sonduruculer ve ilk yardim kitleri goruntulenir\n- Diger normal alanlar soluk gorunur, dikkat dagiticilari azaltir\n- Kritik alanlarda nabiz animasyonu gorursunuz\n\nAcil durum modu gercek bir acil durumda personelin hizla cikis ve guvenlik ekipmanlarini bulmasini saglar. Bu modu tatbikat veya planlama amaciyla da kullanabilirsiniz. Moddayken "Normal Mod" butonuna basarak standart gorunume donebilirsiniz.' },
      { q: 'OperIQ tesis analizi nasil yapilir?', a: '"OperIQ" butonuyla tum tesis icin kapsamli bir AI analizi baslatabilirsiniz. Analiz su bilesenlerden olusur:\n\n- Alan Kullanimı Analizi: Hangi alanlar etkin kullaniliyor, hangileri bosta\n- Risk Degerlendirmesi: Potansiyel tehlike ve sorun bolgeleri\n- Verimlilik Onerisi: Is akisi ve yerlesim optimizasyon onerileri\n- Anomali Tespiti: Normal disi durumlar ve uyarilar\n\nBelirli bir alan icin analiz almak icin o alana tiklayin ve "OperIQ Analiz" butonuna basin. Alan bazinda analiz daha detayli ve odakli sonuclar uretir.\n\nAnaliz sonuclari rapor formatinda sunulur - problemli alanlar, onerilen aksiyonlar ve risk seviyesi yer alir. Onerilen aksiyonlari dogrudan gorev olarak olusturabilirsiniz.' },
    ],
  },
  {
    icon: Cpu, title: 'IoT Cihaz Yonetimi', path: '/iot',
    items: [
      { q: 'IoT cihaz nasil eklenir?', a: '"Cihazlar" sayfasindan "Yeni Cihaz" butonuyla cihaz eklemek icin asagidaki adimlari izleyin:\n\n1. Cihaz ID: Cihazin benzersiz kimlik numarasini girin\n2. Cihaz Adi: Tanimlayici bir isim verin (orn: "Uretim Hatti 1 - Sicaklik Sensoru")\n3. Cihaz Tipi: Sensor, gateway, aktüatör veya kontrolcü secin\n4. Protokol: MQTT, HTTP, CoAP veya Modbus protokolunu secin\n5. Konum: Cihazin fiziksel konumunu belirleyin (tesis haritasindaki alan ile eslestirebilirsiniz)\n6. Alarm Esikleri: Her olcum degeri icin min/max esikleri tanimlayın\n7. "Kaydet" butonuna basin\n\nCihaz eklendikten sonra baglanti bilgileri otomatik uretilir. Bu bilgileri cihaz yapilandirmasinda kullanarak veri gondermeye baslayabilirsiniz. Cihaz ilk verisini gonderdiginde durum "Cevrimici" olarak guncellenir.' },
      { q: 'Alarm esikleri nasil ayarlanir?', a: 'Cihaz detayinda her sensor degeri icin esik degerleri tanimlayabilirsiniz. Esik turleri:\n\n- Minimum Uyari: Deger bu seviyenin altina dustugunde sari uyari olusur\n- Minimum Kritik: Deger bu seviyenin altina dustugunde kirmizi alarm olusur\n- Maksimum Uyari: Deger bu seviyeyi astiginda sari uyari olusur\n- Maksimum Kritik: Deger bu seviyeyi astiginda kirmizi alarm olusur\n\nEsik asildiginda su islemler otomatik gerceklesir:\n1. Cihaz detayinda alarm ikonu goruntulenir\n2. Tesis haritasindaki ilgili alan kirmizi/sari renk alir\n3. Tanimlanan kisilere bildirim gonderilir (e-posta ve platform bildirimi)\n4. Otomasyon kurali tanimlanmissa ilgili aksiyonlar tetiklenir\n\nEsik degerlerini istediginiz zaman guncelleyebilirsiniz. Gecmis alarm kayitlarina cihaz detayindaki "Alarm Gecmisi" sekmesinden ulasabilirsiniz.' },
      { q: 'Cihaz durum izleme ve gecmis verileri', a: 'Her IoT cihazinin detay sayfasinda su bilgiler bulunur:\n\n- Canli Durum: Cihazin su anki durumu (cevrimici, cevrimdisi, alarm)\n- Son Degerler: En son alinan sensor degerleri\n- Trend Grafigi: Secilen zaman araligindaki veri grafigi\n- Baglanti Bilgisi: Son iletisim zamani ve sinyal gucu\n- Alarm Gecmisi: Gecmisteki tum alarm kayitlari\n\nGecmis verileri goruntulrmek icin:\n1. Cihaz detay sayfasini acin\n2. "Gecmis Veriler" sekmesine gecin\n3. Tarih araligini secin\n4. Istediginiz sensor degerlerini secin\n5. Grafik otomatik cizilir - yakinlastirarak detay gorebilirsiniz\n\nGecmis verileri CSV veya Excel formatinda disari aktarabilirsiniz.' },
      { q: 'Cihaz gruplama ve toplu yonetim', a: 'Cihazlari gruplar halinde organize edebilirsiniz. Bu ozellikle cok sayida cihazi olan tesislerde islemleri kolaylastirir.\n\nGrup olusturmak icin:\n1. "Cihazlar" sayfasinda "Gruplar" sekmesine gecin\n2. "Yeni Grup" butonuna basin\n3. Grup adini girin (orn: "Uretim Hatti Sensorleri", "Depo Iklimlendirme")\n4. Gruba cihaz ekleyin\n5. "Kaydet" butonuna basin\n\nGrup uzerinden toplu islemler yapabilirsiniz: toplu alarm esigi guncelleme, toplu aktif/pasif yapma veya grubun genel saglik durumunu tek ekranda izleme. Cihaz listesinde grup filtresi ile belirli bir gruba ait cihazlari hizla bulabilirsiniz.' },
      { q: 'IoT veri gorsellestirme', a: 'IoT verilerini cesitli grafik tipleriyle gorsellestirin:\n\n- Cizgi Grafik: Zaman serisindeki degisimleri takip edin (orn: sicaklik trendi)\n- Gosterge (Gauge): Anlik degeri kadran uzerinde gorun\n- Isı Haritasi: Birden fazla cihazin degerlerini renk matrisi ile karsilastirin\n- Tablo: Tum cihaz degerlerini satirlar halinde gorun\n\nDashboard\'a IoT widgeti eklemek icin dashboard duzenleme modunda "IoT Widget" secenegini kullanin. Her widget bir veya birden fazla cihazin verilerini gosterebilir. Gercek zamanli guncelleme ile veriler canli olarak akar.' },
    ],
  },
  {
    icon: Package, title: 'Stok Yonetimi', path: '/stok',
    items: [
      { q: 'Stok modulu genel bakis', a: 'Stok yonetimi modulu, isletmenizdeki tum malzeme, hammadde, yedek parca ve urunlerin takibini saglar. Ana ekranda su bilgiler yer alir:\n\n- Stok Ozeti: Toplam kalem sayisi, toplam deger, kritik seviyedeki kalemler\n- Kategori Dagilimi: Stoklarinizin kategorilere gore dagilim grafigi\n- Son Hareketler: En son yapilan giris ve cikis islemleri\n- Uyarilar: Minimum stok seviyesinin altina dusen kalemler\n\nSol taraftaki kategori agacindan belirli kategorilere hizla erisebilirsiniz. Ust kisimdaki arama cubugu ile stok kalemi adi, kodu veya barkod numarasi ile arama yapabilirsiniz.' },
      { q: 'Yeni stok kalemi nasil eklenir?', a: 'Stok sayfasinda "Yeni Kalem" butonuna basarak stok kalemi ekleyin:\n\n1. Kalem Adi: Urunun veya malzemenin adini girin\n2. Stok Kodu: Benzersiz bir stok kodu belirleyin (otomatik uretim de mumkun)\n3. Kategori: Uygun kategoriyi secin veya yeni kategori olusturun\n4. Birim: Adet, kg, litre, metre, kutu vb. birimi secin\n5. Minimum Stok Seviyesi: Uyari icin alt limit belirleyin\n6. Maksimum Stok Seviyesi: Ust limit (opsiyonel)\n7. Depo/Lokasyon: Fiziksel depolama konumunu secin\n8. Barkod: Varsa barkod numarasini girin\n9. Tedarikci: Varsayilan tedarikciyi secin\n\nKalem olusturulduktan sonra fotograf ekleyebilir, ek notlar girebilir ve tesis haritasinda konumunu isaretleyebilirsiniz.' },
      { q: 'Stok hareketi (giris/cikis) nasil yapilir?', a: 'Stok hareketi kaydetmek icin iki yontem vardir:\n\nTek Kalem Hareketi:\n1. Stok kalemi detay sayfasini acin\n2. "Hareket Ekle" butonuna basin\n3. Hareket tipini secin: Giris (satin alma, iade, uretim) veya Cikis (kullanim, sevkiyat, fire)\n4. Miktari girin\n5. Aciklama ve referans numarasi ekleyin\n6. "Kaydet" ile hareketi onaylayin\n\nToplu Hareket:\n1. Stok sayfasinda "Toplu Hareket" butonuna basin\n2. Excel sablonunu indirin veya barkod okuyucu ile kalemleri tarat\n3. Her kalem icin miktar ve hareket tipini belirleyin\n4. Onizlemeyi kontrol edin\n5. "Onayla" ile tum hareketleri kaydedin\n\nHer hareket otomatik zaman damgasi ve kullanici bilgisi ile kaydedilir. Hareketleri geri almak mumkun degildir - hatali giris icin ters hareket olusturmaniz gerekir.' },
      { q: 'Stok uyarilari nasil calisir?', a: 'Minimum stok seviyesi tanimlanan kalemlerin stok miktari bu seviyenin altina dustugunde otomatik uyari olusur. Uyari sistemi su sekilde calisir:\n\n1. Stok miktari minimum seviyenin altina duser\n2. Sistem otomatik uyari olusturur ve ilgili kisilere bildirim gonderir\n3. Stok panelinde "Kritik Stok" bolumunde kirmizi ile isaretlenir\n4. Dashboard\'daki stok widgetinda uyari goruntulenir\n5. Otomasyon kurali tanimlanmissa otomatik satinalma talebi olusabilir\n\nUyari seviyeleri:\n- Sari Uyari: Stok miktari minimum seviyeye yaklasti (minimum + %20)\n- Kirmizi Alarm: Stok miktari minimum seviyenin altina dustu\n- Sifir Stok: Stok tamamen tukendi\n\nUyari bildirimlerini kimlerin alacagini stok ayarlarindan yapilandirabilirsiniz.' },
      { q: 'Envanter nasil yuklenir (Excel/CSV)?', a: 'Mevcut envanterinizi toplu olarak platformna yuklemek icin:\n\n1. "Stok" sayfasinda "Icerik Aktar" butonuna basin\n2. "Sablon Indir" ile bos sablon dosyasini alin\n3. Sablonu Excel veya CSV formatinda doldurun. Gerekli alanlar: Kalem Adi, Stok Kodu, Kategori, Birim, Miktar\n4. Doldurulmus dosyayi yukleyin\n5. OperIQ sutunlari otomatik eslestirir - eslestirme onizlemesini kontrol edin\n6. Hatali satirlar varsa duzeltme onerileri goruntulenir\n7. "Kaydet" ile tum kalemleri ice aktarin\n\nMevcut stok kalemlerini guncellemek icin de ayni yontemi kullanabilirsiniz - stok kodu eslesen kalemler guncellenir, yeni kodlar ise yeni kalem olarak eklenir.' },
      { q: 'Stok raporu ve analiz', a: 'Stok modulunde cesitli raporlar ve analizler mevcuttur:\n\n- Stok Durum Raporu: Tum kalemlerin guncel stok miktarlari ve degerleri\n- Hareket Raporu: Belirli tarih araligindaki tum giris ve cikis hareketleri\n- Tüketim Analizi: Kalemlerin tuketim hizi ve trendi\n- Kritik Stok Raporu: Minimum seviyenin altindaki veya yaklasan kalemler\n- Deger Raporu: Kategorilere gore stok degeri dagilimi\n\nRaporlari PDF veya Excel formatinda indirebilirsiniz. OperIQ ile stok verilerinize dayali tahminleme ve optimizasyon onerileri alabilirsiniz - ornegin "Hangi kalemler onumuzdeki ay icinde tukenebilir?" sorusunu sorabilirsiniz.' },
    ],
  },
  {
    icon: Package, title: 'AssetIQ (QR + Stok Zekasi)', path: '/envanter-zeka',
    items: [
      { q: 'AssetIQ modulu nedir?', a: 'AssetIQ, QR kod sistemi ile stok yonetimini derinlemesine entegre eden, operasyonel sureclerle baglantili, yapay zeka destekli bir envanter ve tuketim yonetim sistemidir.\n\nModul su temel ozellikleri icerir:\n- QR Kod Yonetimi: Her stok kalemi ve lokasyon icin QR kod olusturma ve tarama\n- Stok Lokasyonlari: Hiyerarsik depo/raf/bolme yapisi\n- Parti/Lot Takibi: Uretim tarihi, son kullanma tarihi, tedarikci bilgisi\n- Gelismis Hareketler: 7 farkli hareket tipi (Giris, Cikis, Kullanim, Fire, Transfer, Sayim, Rezervasyon)\n- Gorev Bazli Stok Ayirma: Gorevler icin stok rezervasyonu\n- Hizli Tuketim: Saha calisanlari icin tek dokunusla stok dusme\n- OperIQ Analiz: Sektor bazli yapay zeka destekli stok analizi\n- Satin Alma Sorumlusu: Kritik stok bildirimlerinin dogru kisilere ulasmasi' },
      { q: 'QR kod nasil olusturulur ve kullanilir?', a: 'QR kodlari olusturmak icin:\n1. "AssetIQ" sayfasinda "QR Yonetimi" sekmesine gidin\n2. "Yeni QR" butonuna basin\n3. Varlik tipini secin (Stok Kalemi, Lokasyon, Ekipman, IoT Cihaz, Tesis Alani)\n4. Iliskili varligi secin\n5. Opsiyonel etiket ekleyin\n6. "QR Olustur" butonuna basin\n\nQR taramak icin:\n- "QR Tara" bolumune QR kodunu girin veya mobil uygulamadan okutun\n- Sistem otomatik olarak bagli varligi acar\n- Sektor sablonuna gore uygun ekran ve aksiyonlar goruntulenir\n\nOrnekler:\n- Uretimde QR okutunca makine bagli parcalar ekrani\n- Saglikta QR okutunca ilac/tibbi malzeme ekrani\n- Perakendede QR okutunca raf stogu ekrani' },
      { q: 'Stok lokasyonlari nasil yonetilir?', a: 'Lokasyonlar hiyerarsik bir yapida organize edilir (Depo > Raf > Bolme).\n\n1. "Lokasyonlar" sekmesine gidin\n2. "Yeni Lokasyon" butonuna basin\n3. Lokasyon bilgilerini girin: Ad, Kod, Kategori, Departman\n4. Ust lokasyon secerek alt lokasyon olusturun\n\nLokasyon kategorileri:\n- Ana Depo, Raf, Uretim Hatti, Soguk Depo, Bakim Deposu, Arac, Dagitim Noktasi, Servis Alani, Laboratuvar\n\nHer lokasyondaki stok kalemleri ve miktarlari goruntulenebilir. Lokasyon agaci gorunumuyle tum yapi tek bakista gorulur.' },
      { q: 'Parti/Lot takibi nasil yapilir?', a: 'Batch/Lot yonetimi ozellikle gida, saglik, kimya ve FMCG sektorlerinde zorunludur.\n\n1. "Parti/Lot" sekmesine gidin\n2. "Yeni Parti" butonuna basin\n3. Stok kalemini secin\n4. Parti numarasini girin (orn: LOT-2026-001)\n5. Uretim tarihi ve son kullanma tarihini girin\n6. Tedarikci ve lokasyon bilgilerini ekleyin\n\nSistem otomatik olarak:\n- Son kullanma tarihi yaklasan partileri (30 gun) uyari olarak isaretler\n- Son kullanma tarihi gecmis partilerin durumunu gunceller\n- Dashboard\'da "SKT Yaklasan Partiler" listesini gosterir' },
      { q: 'Hizli tuketim modu nasil kullanilir?', a: 'Saha calisanlari icin minimum input ile hizli stok dusumu:\n\n1. QR kodu okutun veya "Hizli Tuketim" butonuna basin\n2. Stok kalemini secin\n3. Miktar secin (+1, +5, +10 veya ozel miktar)\n4. "Kaydet" ile tek dokunusta stok dusumu yapin\n\nHizli tuketim otomatik olarak:\n- InventoryTransaction kaydeder\n- ConsumptionEvent olusturur\n- StockMovement (legacy) gunceller\n- Kritik seviye kontrol edip gerekirse uyari tetikler\n\nBu ozellik sektor bazli farkli isimlerle gosterilir (uretimde "Hizli Kullanim", saglikta "Hizli Sarf Dusum", perakendede "Hizli Raf Eksiltme").' },
      { q: 'Stok rezervasyonu nasil yapilir?', a: 'Gorevler icin stok ayirma islemleri:\n\n1. "Rezervasyonlar" sekmesine gidin\n2. "Yeni Rezervasyon" butonuna basin\n3. Stok kalemini ve miktarini secin\n4. Hangi gorev icin oldugunu belirtin\n5. Son gecerlilik tarihi ekleyin (opsiyonel)\n\nRezervasyonlar stok miktarindan dusulmez, ancak kullanilabilir miktar hesaplamasinda dikkate alinir. Gorev tamamlandiginda rezervasyon otomatik kullanilir. Suresi dolan rezervasyonlar otomatik kapatilir.' },
      { q: 'Satin alma sorumlusu nasil tanimlanir?', a: 'Kritik stok bildirimlerinin dogru kisilere ulasmasi icin:\n\n1. "Satin Alma" sekmesine gidin\n2. "Sorumlu Ekle" butonuna basin\n3. Kullaniciyi secin\n4. Sorumluluk tipini belirleyin: Ana Satin Alma Sorumlusu, Yedek Sorumlu veya Key Account Manager\n5. Sorumlu oldugu departmanlari secin (bos birakarak tum sirket genelini kaplayabilir)\n\nKritik veya risk gosteren stok durumunda:\n- Stogun oldugu departmanin mudurune bildirim ve mesaj gider\n- Ilgili satin alma sorumlularina bildirim ve mesaj gider\n- Satin alma departmani yoksa key account manager\'a bildirim gider' },
      { q: 'Sektor sablonlari ve terminoloji', a: 'AssetIQ modulu 10 farkli sektore uyarlanabilir terminoloji sunar:\n\n1. Uretim: Yedek Parca, Sarf Malzeme, Uretim Hatti\n2. Gida: Hammadde, Ambalaj, Soguk Depo, Parti/Lot\n3. Saglik: Tibbi Malzeme, Ilac, Ilac Odasi, Hasta Kullanimi\n4. Lojistik: Koli, Palet, Sevkiyat Cikisi, Dagitim Noktasi\n5. Perakende: Urun, Raf Stogu, Satis Cikisi, Magaza Deposu\n6. Kamu: Ekipman, Teknik Malzeme, Hizmet Binasi\n7. Egitim: Egitim Materyali, Laboratuvar Sarfi\n8. Enerji: Kritik Parca, Trafo Sahasi, Bakim Kullanimi\n9. HoReCa: Mutfak Sarfi, Servis Malzemesi, Soguk Oda\n10. IT: Network Ekipmani, Server Odasi, Kurulum Cikisi\n\nSirketinizin sektoru secildiginde tum ekranlar, hareket isimleri ve OperIQ yorumlari otomatik olarak sektor diline uyarlanir.' },
      { q: 'IoT cihaz sorumlusu ve bildirim sistemi', a: 'Her IoT cihazina bir veya birden fazla sorumlu atanabilir:\n\n1. "IoT Sorumlu" bolumune gidin\n2. Cihazi ve sorumlu kisiyi secin\n3. Sorumluluk tipini belirleyin (Ana veya Yedek)\n4. Bildirim tercihlerini ayarlayin:\n   - Alert durumunda bildirim\n   - Kritik durumda bildirim\n   - Offline durumda bildirim\n   - Rutin durum raporu (gunde 2 kere: 09:00 ve 17:00)\n\nRisk veya kritik durumda sorumlu kisiye otomatik bildirim ve mesaj gider. Gunde 2 kere tum sorumlularin sorumlu oldugu cihazlarin genel durum ozeti gonderilir.' },
      { q: 'OperIQ envanter analizi', a: 'OperIQ, sektor baglamina gore stok verilerini analiz eder:\n\n1. "OperIQ Zeka" sekmesine gidin\n2. "Analiz Et" butonuna basin\n3. Sistem su analizleri yapar:\n   - Hizli tukenen kalemler ve risk degerlendirmesi\n   - Anormal tuketim kaliplari\n   - Tukenme tahmini (kac gun yeter)\n   - Batch/lot son kullanma riskleri\n   - IoT cihaz durumlari ile stok iliskisi\n   - Fazla stok tespiti\n   - Gorev-stok uyumlulugu\n   - Tedarik planlama onerileri\n\nHer icgoru aksiyon odaklidir ve sektor terminolojisinde sunulur. Ornegin uretimde "Rulman tuketimi son 10 gunde %40 artti", saglikta "Bu tibbi sarf beklenenden hizli tuketildi" gibi.' },
    ],
  },
  {
    icon: FolderOpen, title: 'Dosya Yonetimi', path: '/dosyalar',
    items: [
      { q: 'Dosya nasil yuklenir?', a: 'Dosya yonetimi modulu ile tum kurumsal dokumanlarinizi organize edebilirsiniz. Dosya yuklemek icin:\n\n1. Sol menuden "Dosyalar" a gidin\n2. Yuklemek istediginiz klasore girin (veya yeni klasor olusturun)\n3. "Dosya Yukle" butonuna basin veya dosyalari dogrudan surukleyip birakin\n4. Desteklenen formatlar: Word (.docx), Excel (.xlsx), PDF (.pdf), gorseller (JPG, PNG, GIF), metin (.txt, .csv)\n5. Maksimum dosya boyutu: 50 MB\n6. Birden fazla dosyayi ayni anda yukleyebilirsiniz\n\nYuklenen her dosya icin yukleyen kisi, tarih ve boyut bilgisi otomatik kaydedilir. Dosyalara aciklama ve etiket ekleyerek aranabilirligini artirabilirsiniz.' },
      { q: 'Klasor yapisi ve organizasyon', a: 'Dosyalarinizi klasor hiyerarsisi ile duzenleyin:\n\n1. "Yeni Klasor" butonuna basin\n2. Klasor adini girin\n3. Ust klasor secin (alt klasor olusturmak icin)\n4. Erisim yetkisini belirleyin (tum kullanicilar veya belirli departmanlar)\n\nOnerdgimiz klasor yapisi:\n- Genel Dokumanlar: Sirket genelinde paylasilan belgeler\n- Departman Dosyalari: Her departman icin ayri klasor\n- Proje Dosyalari: Projelere ozel dokumanlar\n- Sablonlar: Form sablonlari ve standart dokumanlar\n- Arsiv: Eski ve tamamlanmis proje dosyalari\n\nKlasorleri surukleyerek tasiyabilir, yeniden adlandiabilir veya silebilirsiniz (icindeki dosyalar cop kutusuna tasinir).' },
      { q: 'Dosya goruntulerme ve on izleme', a: 'Dosya adina tiklayarak icerigi platform icerisinde goruntuleyebilirsiniz. On izleme desteklenen formatlar:\n\n- PDF: Sayfa sayfa goruntuleme, yakinlastirma, arama\n- Word (.docx): Dokuman icerigi formatlaniyla birlikte goruntulenir\n- Excel (.xlsx): Tablo gorunumunde, sayfa sekmelerı ile\n- Gorseller (JPG, PNG, GIF): Tam boyut goruntuleme, yakinlastirma\n- Metin Dosyalari (.txt, .csv): Duz metin olarak goruntuleme\n\nOn izleme ekraninda su islemler mevcuttur:\n- Indir: Dosyayi bilgisayariniza indirin\n- Paylas: Dosya linkini baska kullanicilarla paylasin\n- Yazdir: Dosyayi dogrudan yaziciya gonderin\n- Sil: Dosyayi cop kutusuna gonderin' },
      { q: 'Dosya arama ve filtreleme', a: 'Dosya modulundeki arama ozellikleri:\n\n- Hizli Arama: Ust kisimdaki arama cubuguna dosya adini yazin\n- Tip Filtresi: Belirli dosya turlerini filtreleyin (PDF, Excel, Gorsel vb.)\n- Tarih Filtresi: Belirli zaman araliginda yuklenen dosyalari bulun\n- Yuikleyen Kisi: Belirli bir kullanicinin yukledigi dosyalari listeleyin\n- Etiket: Dosyalara eklenmis etiketlere gore filtreleyin\n\nArama sonuclari dosya adi, boyut, yuklenme tarihi ve konumu ile birlikte listelenir. Sonuca tiklayarak dogrudan dosyayi goruntuleyebilirsiniz.' },
    ],
  },
  {
    icon: Zap, title: 'Otomasyon & Kurallar', path: '/otomasyon',
    items: [
      { q: 'Otomasyon kurali nasil olusturulur?', a: '"Otomasyon" sayfasindan adim adim sihirbaz ile otomasyon kurali tanimlayin. Kural olusturma adimlari:\n\n1. Tetikleyici (Trigger) secin: Kurali baslatacak olayi belirleyin\n   - Gorev gecikti\n   - Rapor olusturuldu\n   - Stok seviyesi dustu\n   - IoT alarm tetiklendi\n   - KPI hedefi asildi veya geriledi\n   - Belirli bir zaman geldi (zamanlanmis)\n\n2. Kosul (Condition) ekleyin (opsiyonel): Tetikleyicinin hangi kosullarda calisacagini belirleyin\n   - Departman filtresi\n   - Oncelik seviyesi\n   - Belirli kullanici veya rol\n\n3. Aksiyon (Action) tanimlayin: Tetiklendiginde ne olacagini belirleyin\n   - Bildirim gonder (platform, e-posta)\n   - Gorev olustur\n   - Durum guncelle\n   - Rapor olustur\n   - OperIQ analizi baslat\n\n4. Kurali test edin ve aktif hale getirin\n\nOrnek kural: "Kritik oncelikli gorev 24 saat geciktiyse, departman mudurune e-posta gonder ve ust yoneticiye bildirim at"' },
      { q: 'Otomasyon kurallarini yonetme', a: 'Mevcut kurallari yonetmek icin "Otomasyon" sayfasindaki kural listesini kullanin:\n\n- Aktif/Pasif: Her kuralın yanindaki toggle ile kurali aktif veya pasif yapabilirsiniz\n- Duzenleme: Kural satirina tiklayarak detaylarini degistirin\n- Kopyalama: Mevcut bir kurali kopyalayarak benzer yeni kural olusturun\n- Silme: Artik gerekmeyen kurallari silin\n- Calisma Gecmisi: Her kurallin ne zaman tetiklendigi ve ne sonuc verdigi kayitlidir\n\nKurallar oncelik sirasina gore islenir. Ayni tetikleyiciye sahip birden fazla kural varsa hepsi ayri ayri calisir. Kurallarin calisma gecmisini inceleyerek beklenmedik davranislari tespit edebilirsiniz.' },
      { q: 'Hazir otomasyon sablonlari', a: 'Hizli baslamak icin hazir otomasyon sablonlarini kullanabilirsiniz. Sol taraftaki "Sablonlar" bolumunde sik kullanilan senaryolar mevcuttur:\n\n- Gorev Gecikme Uyarisi: Geciken gorevler icin otomatik bildirim\n- Kritik Rapor Eskalasyonu: Kritik siddetteki raporlarin ust yonetime iletilmesi\n- Stok Yenileme Talebi: Minimum stok altina dusen kalemler icin satin alma talebi\n- IoT Alarm Yaniti: Sensor alarmi tetiklendiginde gorev olusturma\n- Haftalik Ozet: Her pazartesi gunluk ozet rapor olusturma\n\nSablonu secin, gerekli ayarlari yapin (departman, kisiler vb.) ve "Aktif Et" butonuna basin. Sablonlari temel alarak kendi ozel kurallarinizi da olusturabilirsiniz.' },
      { q: 'Otomasyon loglari ve hata ayiklama', a: 'Her otomasyon kurali calistiğinda detayli log kaydı olusturulur. Loglari incelemek icin:\n\n1. Otomasyon sayfasinda ilgili kurala tiklayin\n2. "Calisma Gecmisi" sekmesine gecin\n3. Her calisma icin tarih, tetikleyici bilgisi, kosul sonucu ve aksiyon durumu goruntulenir\n\nLog durumlari:\n- Basarili (yesil): Kural basariyla calisti ve aksiyon tamamlandi\n- Atlandı (sari): Kural tetiklendi ama kosul saglanmadi\n- Hata (kirmizi): Kural calisti ama aksiyonda hata olustu\n\nHata durumlarinda hata detayini inceleyerek sorunu teshis edebilirsiniz. Sik karsilasilan hatalar: hedef kullanici bulunamadi, e-posta gonderilemedi veya hedef kaynak mevcut degil.' },
    ],
  },
  {
    icon: Workflow, title: 'Is Akislari (Workflows)', path: '/otomasyon',
    items: [
      { q: 'Is akisi nedir ve ne ise yarar?', a: 'Is akislari, birden fazla adimdan olusan ve belirli bir siraya ile ilerlemesi gereken is sureclerini dijitallestirmenize olanak tanir. Ornegin bir satin alma talebi sureci su adimlari icererbilir: talep olusturma, sef onay, mudur onay, satin alma, teslim alma, kalite kontrol.\n\nIs akislarinin faydalari:\n- Surecler standartlasir ve herkes ayni adimlari izler\n- Her adimda kimin ne yapacagi nettir\n- Onay mekanizmalari ile kontrol saglanir\n- Surecin hangi asamada oldugu anlik goruntulenir\n- Geciken adimlar icin otomatik hatirlatma gonderilir\n- Gecmis akis kayitlari ile performans analizi yapilir' },
      { q: 'Yeni is akisi nasil olusturulur?', a: '"Is Akislari" sayfasinda "Yeni Akis" butonuna basin. Is akisi tasarimcisi acilir. Adimlari:\n\n1. Akis Adi: Sureci tanimlayan bir isim verin (orn: "Satin Alma Talebi", "Izin Basvurusu")\n2. Baslangic Kosulu: Akisin nasil baslatilacagini secin (manuel, otomatik tetikleme)\n3. Adimlar Ekleyin: Her adim icin:\n   - Adim adi ve aciklamasi\n   - Sorumlu kisi veya rol (orn: "Departman Muduru")\n   - Adim tipi: Onay, Bilgi Girisi, Bildirim, Dallanma veya Paralel Islem\n   - Tamamlanma suresi (opsiyonel SLA)\n4. Baglantilari Tanimlayin: Adimlarin hangi siraya ile ilerleyecegini belirleyin\n5. Dallanma: "Onaylandi" ise bir yol, "Reddedildi" ise baska bir yol tanimlayabilirsiniz\n6. "Kaydet ve Aktif Et" ile akisi yayinlayin\n\nAkis tasarimcisinda surukle-birak ile adimlar ekleyip siralarini degistirebilirsiniz.' },
      { q: 'Is akisi sablonlari', a: 'Hizlica baslamak icin hazir is akisi sablonlari mevcuttur:\n\n- Satin Alma Talebi: Talep - Sef Onay - Mudur Onay - Satinalma - Teslim Alma\n- Izin Basvurusu: Basvuru - Yonetici Onay - IK Onay - Kayit\n- Bakim Talebi: Ariza Bildirimi - Onceliklendirme - Atama - Uygulama - Kontrol\n- Yeni Personel Ise Giris: Dokuman Toplama - IK Kayit - IT Hesap Acma - Egitim - Departman Atama\n- Kalite Kontrol: Numune Alma - Test - Degerlendirme - Onay/Red\n\nSablon secmek icin:\n1. "Yeni Akis" butonuna basin\n2. "Sablondan Olustur" sekmesine gecin\n3. Istediginiz sablonu secin\n4. Adimlari ihtiyaciniza gore duzenleyin\n5. Kaydedin ve aktif edin\n\nSablonlar iyi bir baslangic noktasidir - uzerine ekleme ve duzenleme yaparak kendi sureclerinize uyarlayin.' },
      { q: 'Calisan is akisi orneklerini takip etme', a: 'Aktif is akisi orneklerini (calisan surecler) takip etmek icin "Is Akislari" sayfasindaki "Calisan Akislar" sekmesine gecin. Burada su bilgiler goruntulenir:\n\n- Akis Adi ve Baslatan Kisi\n- Mevcut Adim: Surecin hangi asamada oldugu\n- Sorumlu Kisi: Su an aksiyonu beklenen kisi\n- Baslama Tarihi ve Sure\n- Durum: Devam Ediyor, Tamamlandi, Beklemede, Iptal\n\nBir akis ornegine tiklayarak detayli zaman cizelgesini gorebilirsiniz. Her adimda kimin ne zaman ne yaptigini, harcanan sureyi ve varsa eklenen notlari inceleyebilirsiniz.\n\nBeklemede olan adiminiz varsa bildirim alirsiniz. Ilgili adima tiklayarak onay verin, reddedin veya bilgi girin.' },
      { q: 'Is akisi raporlari ve performans', a: 'Is akisi performansini analiz etmek icin su raporlara erisebilirsiniz:\n\n- Ortalama Tamamlanma Suresi: Her akis tipi icin ortalama tamamlanma suresi\n- Darbogaz Analizi: En uzun suren adimlar ve bekleme noktaları\n- Tamamlanma Orani: Basariyla tamamlanan ve iptal edilen akis oranlari\n- Kisi Bazinda Performans: Her kullanicinin onay/red suresi ve sayisi\n\nBu raporlar is sureclerinizdeki verimsizlikleri tespit etmenize ve iyilestirmeler yapmaniza yardimci olur. OperIQ\'ya "Is akislarimda darbogazlar nerede?" diye sorarak AI destekli analiz alabilirsiniz.' },
    ],
  },
  {
    icon: Bell, title: 'Bildirimler',
    items: [
      { q: 'Bildirimler nasil goruntulenir?', a: 'Bildirimlere erismenin birden fazla yolu vardir:\n\n- Ust Bar: Sag ustteki can ikonuna tiklayin - okunmamis bildirimler kirmizi daire ile gosterilir\n- Bildirim Paneli: Can ikonuna tiklayinca acilan panelde son bildirimler listelenir\n- Bildirim Sayfasi: "Tum Bildirimleri Gor" linkine tiklayarak tam sayfa bildirim listesine ulasin\n\nBildirim turleri:\n- Gorev Bildirimi: Size atanan yeni gorev, durum degisikligi, yorum eklenmesi\n- Rapor Bildirimi: Yeni rapor, durum guncelleme, OperIQ analiz sonucu\n- IoT Alarm: Sensor esik asimi, cihaz cevrimdisi uyarisi\n- Stok Uyarisi: Minimum stok seviyesi altina dusme\n- Is Akisi: Onay bekleyen adim, akis tamamlanma\n- Sistem: Platform guncelleme, bakim duyurusu' },
      { q: 'Bildirim tercihlerini ayarlama', a: 'Hangi bildirileri alacaginizi ve nasil alacaginizi profil ayarlarindan yapilandirabilirsiniz:\n\n1. Sag ustteki profil ikonunuza tiklayin\n2. "Bildirim Tercihleri" bolumune gidin\n3. Her bildirim kategorisi icin su kanallari ayarlayin:\n   - Platform Bildirimi: Ust bardaki can ikonu uzerinden\n   - E-posta: Giris e-postaniza gonderilir\n   - Her ikisi: Hem platform hem e-posta ile bildirim alin\n   - Kapali: Bu kategori icin bildirim almayin\n\nKategoriler: Gorevler, Raporlar, IoT Alarmlar, Stok Uyarilari, Is Akislari, Mesajlar, Sistem Duyurulari\n\nOneri: Kritik IoT alarmlari ve gorev atamalari icin hem platform hem e-posta bildirimini acik tutmanizi tavsiye ederiz. Daha az oncelikli bildirimler icin sadece platform bildirimini kullanabilirsiniz.' },
      { q: 'Bildirimleri okundu olarak isaretleme', a: 'Bildirimleri yonetmek icin su islemleri yapabilirsiniz:\n\n- Tek Bildirim: Bildirime tiklayarak otomatik okundu olarak isaretlenir ve ilgili sayfaya yonlendirilirsiniz\n- Toplu Isaretleme: Bildirim panelinin ustundeki "Tumunu Okundu Isaretle" butonuyla tum bildirimleri okundu yapin\n- Filtreleme: Bildirim sayfasinda "Okunmamis" filtresi ile sadece yeni bildirimleri gorun\n- Silme: Eski bildirimleri tek tek veya toplu olarak silebilirsiniz\n\nOkunmamis bildirim sayisi ust bardaki can ikonunun yaninda kirmizi daire icinde gosterilir. Bildirimlerinizi duzenli olarak kontrol etmeniz onemli gorevleri kacirmamamanizi saglar.' },
      { q: 'E-posta bildirimleri ve ozetler', a: 'Platform icerisindeki bildirimlere ek olarak e-posta uzerinden de bilgilendirme alabilirsiniz:\n\n- Anlik E-posta: Kritik bildirimlerde anlik e-posta gonderilir\n- Gunluk Ozet: Her gun sabah saat 08:00\'de onceki gunun ozetini iceren e-posta\n- Haftalik Ozet: Her pazartesi sabahi haftalik performans ozetini iceren e-posta\n\nE-posta bildirimlerini profil ayarlarindan acip kapatabilirsiniz. E-postalardaki "Platforma Git" butonu ile dogrudan ilgili sayfaya yonlendirilirsiniz.\n\nNot: E-posta bildirimlerinin gelmesi icin gecerli bir e-posta adresinin kayitli olmasi gerekir. Spam klasorunuzu de kontrol etmeyi unutmayin.' },
    ],
  },
  {
    icon: Lock, title: 'Guvenlik & Yetkilendirme',
    items: [
      { q: 'Yetki sistemi nasil calisir?', a: 'ActLedger\'in yetki sistemi 8 seviyeli bir hiyerarsi uzerine kurulmustur. Her kullaniciya atanan rol, platform icerisinde ne gorebilecegini ve ne yapabilecegini belirler.\n\nTemel prensipler:\n- Her ust seviye, altindaki tum seviyelerin yetkilerini otomatik olarak icerir\n- Departman bazinda erisim sinirlamasi vardir - kullanicilar yalnizca kendi departmanlarinin verilerini gorur (yonetici rolleri haric)\n- Bazi islemler (kullanici ekleme, otomasyon olusturma, ayarlar degistirme) yalnizca belirli rol seviyelerinde mumkundur\n- Tum erisim ve islem kayitlari loglanir (denetim izi)\n\nRol atamasi Super Admin veya Genel Mudur tarafindan yapilir. Bir kullanicinin rolunu degistirmek icin "Kullanicilar" sayfasindan kullanici profilini duzenleyin.' },
      { q: 'Her rol ne yapabilir?', a: 'Detayli rol yetki tablosu:\n\nIsci (Seviye 1):\n- Kendisine atanan gorevleri gorebilir ve tamamlayabilir\n- Form doldurabilir\n- Kendi profilini gorebilir\n\nTeknisyen (Seviye 2):\n- Isci yetkilerine ek olarak saha raporu olusturabilir\n- IoT verilerini gorebilir (salt okunur)\n\nUsta (Seviye 3):\n- Gorev olusturabilir ve kendi ekibine atayabilir\n- Stok goruntuleme\n\nSupervizor (Seviye 4):\n- Departmanindaki tum gorev ve raporlari gorebilir\n- Stok hareketi yapabilir\n- Dosya yukleme ve paylasma\n\nSef (Seviye 5):\n- Departman KPI\'larini yonetebilir\n- Is akisi olusturabilir\n- Raporlari onaylayabilir\n\nMudur (Seviye 6):\n- Birden fazla departmani yonetebilir\n- Kullanici ekleyebilir\n- Otomasyon kurali olusturabilir\n\nDirektor (Seviye 7):\n- Tum departmanlara tam erisim\n- Tesis haritasi yonetimi\n- Gelismis raporlama\n\nGenel Mudur (Seviye 8):\n- Tam yetki - tum modullere ve sistem ayarlarina erisim' },
      { q: 'Sifre guvenligi ve politikalari', a: 'ActLedger guclu sifre politikasi uygular:\n\n- Minimum 8 karakter uzunluk\n- En az 1 buyuk harf, 1 kucuk harf, 1 rakam ve 1 ozel karakter\n- Son 5 sifrenin tekrar kullanilmasi engellenir\n- 90 gunde bir sifre degistirme hatirlatmasi\n\nSifre guvenligi icin oneriler:\n- Kolay tahmin edilebilecek sifreler kullanmayin (dogum tarihi, isim, "123456" vb.)\n- Her platform icin farkli sifre kullanin\n- Sifrenizi baskasi ile paylasmayın\n- Sifre yoneticisi uygulamasi kullanmanizi oneriniz\n\nSifrenizi unutursaniz giris ekranindaki "Sifremi Unuttum" linkini kullanin. E-postaniza gelen sifirlama baglantisi 24 saat gecerlidir. 5 basarisiz giris denemesinden sonra hesabiniz gecici olarak kilitlenir - 15 dakika bekleyin veya yoneticinizden kilidi acmasini isteyin.' },
      { q: 'Oturum guvenligi ve ciksiz yapma', a: 'Platformda oturum guvenligi su sekilde calisir:\n\n- Otomatik Cikis: 30 dakika islem yapilmadiginda oturum otomatik olarak sonlandirilir\n- Tek Cihaz Politikasi: Ayni hesap ile ayni anda birden fazla cihazdan giris yapilabilir ancak her cihaz ayri oturum olarak izlenir\n- Guvenli Cikis: Sag ustteki profil menusunden "Cikis Yap" butonuna basarak oturumunuzu guvenli sekilde kapatın\n\nSupheli bir giris fark ederseniz:\n1. Hemen sifrenizi degistirin\n2. Yoneticinize bildirin\n3. "Tum Oturumlari Kapat" secenegi ile diger cihazlardaki oturumlarinizi sonlandirin\n\nPlatform, her giris islemini tarih, saat, IP adresi ve cihaz bilgisi ile loglar. Bu kayitlar guvenlik denetimi icin saklanir.' },
    ],
  },
  {
    icon: MessageSquare, title: 'Mesajlasma',
    items: [
      { q: 'Mesaj nasil gonderilir?', a: 'Ust menudeki mesaj ikonuna tiklayin veya sol menuden "Mesajlar"a gidin. Mesaj gonderme adimlari:\n\n1. "Yeni Mesaj" butonuna basin\n2. Alici secin - kullanici rehberinden isim veya departman arayarak secim yapin\n3. Birden fazla alici ekleyebilirsiniz (grup mesaji)\n4. Mesajinizi yazin\n5. Gerekirse dosya ekleyin (resim, dokuman vb.)\n6. "Gonder" butonuna basin veya Ctrl+Enter kisayolunu kullanin\n\nMesajlar aninda iletilir ve aliciya bildirim gonderilir. Gonderdiginiz mesajlari "Gonderilenler" klasorunde gorebilirsiniz.' },
      { q: 'Mesaj gecmisi ve arama', a: 'Tum mesajlariniz konusmalar halinde saklanir. Bir kisiyle olan tum yazismaniz kronolojik sirada goruntulenir.\n\nMesaj aramak icin:\n- Mesajlar sayfasinin ustundeki arama cubuguna anahtar kelime yazin\n- Sonuclar mesaj icerigi ve gonderen/alan bilgisi ile listelenir\n- Sonuca tiklayarak ilgili konusmaya yonlendirilirsiniz\n\nMesajlari silmek icin mesaj uzerinde sag tiklayip "Sil" secenegini secin. Silinen mesajlar sadece sizin tarafinizdan kaldirilir, alicinin mesaj gecmisinde kalir.' },
      { q: 'Grup mesajlari ve departman iletisimi', a: 'Birden fazla kisiye ayni anda mesaj gondermek icin grup mesajlasmayi kullanin:\n\n1. "Yeni Mesaj" butonuna basin\n2. Alici alaninda birden fazla kisi secin veya departman adi yazarak tum departmani ekleyin\n3. Mesajinizi yazip gonderin\n4. Tum alicilar mesaji ve yanitlari gorebilir\n\nDepartman bazli mesajlasma icin departman adini alici olarak secin - o departmandaki tum kullanicilar mesaji alir. Bu ozellik duyurular ve genel bilgilendirmeler icin cok kullanislidir.' },
      { q: 'Mesajlara dosya ve medya ekleme', a: 'Mesajlara dosya eklemek icin mesaj yazma alanindaki ataç ikonuna tiklayin veya dosyayi dogrudan mesaj alanina surukleyin.\n\nDesteklenen dosya turleri:\n- Gorseller: JPG, PNG, GIF (on izleme olarak goruntulenir)\n- Dokumanlar: PDF, Word, Excel (indirme linki olarak goruntulenir)\n- Diger: Metin dosyalari, CSV dosyalari\n\nMaksimum dosya boyutu: 25 MB. Birden fazla dosya ekleyebilirsiniz. Gorseller kucuk on izleme olarak mesajda gorunur ve tiklayinca buyuk boyutta acilir.' },
    ],
  },
  {
    icon: Shield, title: 'Kisayollar & Ipuclari',
    items: [
      { q: 'Klavye kisayollari nelerdir?', a: '"?" tusuna basarak kisayol listesini gorun. Tum temel kisayollar:\n\nNavigasyon Kisayollari:\n- g + d: Dashboard (Kokpit) sayfasina git\n- g + t: Gorevler sayfasina git\n- g + r: Raporlar sayfasina git\n- g + k: Kullanicilar sayfasina git\n- g + h: Harita sayfasina git\n- g + s: Stok sayfasina git\n- g + i: IoT Cihazlar sayfasina git\n- g + m: Mesajlar sayfasina git\n\nIslem Kisayollari:\n- n: Yeni olusturma (bulundugunuz sayfaya gore gorev, rapor vb.)\n- /: Arama cubuguna odaklan\n- Esc: Acik pencere veya paneli kapat\n- Ctrl + Enter: Formu gonder veya mesaj gonder\n\nBu kisayollari kullanarak fare kullanmadan hizlica platformda gezinebilirsiniz.' },
      { q: 'Platformu verimli kullanma ipuclari', a: 'Deneyiminizi gelistirmek icin su ipuclarini uygulayin:\n\n- Dashboard\'unuzu ozellestirin: En sik baktiginiz verileri widget olarak dashboard\'a ekleyin\n- Filtreleri kaydedin: Sik kullandiginiz filtre kombinasyonlarini kaydederek tek tikla ulasin\n- Kisayollari ogrenin: Klavye kisayollari ile islemlerinizi cok daha hizli yapabilirsiniz\n- OperIQ\'yu kullanin: Karmasik sorular icin yapay zeka asistanina dogal dilde soru sorun\n- Bildirimleri ayarlayin: Gereksiz bildirimleri kapatarak dikkat daginikligini azaltin\n- Mobil uygulamayi kurun: Sahada calisirken mobil uygulama ile gorev tamamlayin ve rapor gonderin\n- Duzenli veri girisi: KPI degerleri ve stok hareketlerini guncel tutun - otomasyon kurallari dogru veriye ihtiyac duyar' },
      { q: 'Tarayici uyumlulugu ve oneriler', a: 'ActLedger su tarayicilarda en iyi performansi sunar:\n\n- Google Chrome (onerilen) - en son surum\n- Mozilla Firefox - en son surum\n- Microsoft Edge - en son surum\n- Safari (macOS) - en son surum\n\nEn iyi deneyim icin:\n- Tarayicinizi her zaman guncel tutun\n- JavaScript\'in aktif oldugundan emin olun\n- Pop-up engelleyicinin ActLedger adresini beyaz listeye aldigindan emin olun\n- Minimum 1280x720 ekran cozunurlugu onerilir\n- Stabil internet baglantisi (en az 2 Mbps) gereklidir' },
      { q: 'Yardim ve destek alma', a: 'Sorun yasadiginizda veya yardima ihtiyac duydugunuzda su kaynaklari kullanin:\n\n- Bu Kilavuz: Sol menudeki "Kullanim Kilavuzu" sayfasi (su an buradasiniz)\n- OperIQ Asistan: Sag alttaki sohbet balonuna tiklayarak AI asistana sorun\n- Destek Talebi: Profil menusundeki "Destek" bolumunden destek talebi olusturun\n- E-posta Destek: Teknik sorunlar icin destek ekibine e-posta gonderin\n\nDestek talebi olustururken su bilgileri eklemeniz cozum suresini kisaltir:\n- Sorunun ne oldugunu ve ne zaman basldigini aciklayin\n- Hangi sayfada veya moduldeki oldugunu belirtin\n- Ekran goruntusu ekleyin (mumkunse)\n- Hangi tarayici ve cihazi kullandiginizi belirtin' },
    ],
  },
  {
    icon: HelpCircle, title: 'Sik Sorulan Sorular (SSS)',
    items: [
      { q: 'Sifresini unutan kullaniciya nasil yardimci olunur?', a: 'Kullanici sifremi unuttum linkinden sifre sifirlama yapabilir. Eger e-postasina erisimi yoksa, yonetici (Mudur seviyesi ve ustu) kullanicinin profilinden "Sifre Sifirla" butonuna basarak yeni gecici sifre uretebilir. Gecici sifre kullaniciya iletilir ve ilk giriste degistirilmesi gerekir.\n\nNot: Guvenlik nedeniyle mevcut sifreleri goremezsiniz - sadece yeni gecici sifre uretebilirsiniz.' },
      { q: 'Veri kaybi yasanir mi? Yedekleme nasil calisir?', a: 'ActLedger otomatik yedekleme sistemi ile verileriniz guvendedir:\n\n- Veritabani yedeklemesi: Gunluk otomatik yedekleme yapilir\n- Dosya yedeklemesi: Yuklenen tum dosyalar redundant olarak saklanir\n- Veri tutma suresi: Silinen veriler 30 gun boyunca geri alinabilir\n\nPlatformda yaptiginiz tum degisiklikler anlik olarak kaydedilir. Internet baglantisi koptuğunda mobil uygulamadaki veriler cihazda saklanir ve baglanti geri geldiginde otomatik senkronize edilir. Veri kaybi riski minimumdur.' },
      { q: 'Platformda hata veya yavaslik yasiyorum, ne yapmaliyim?', a: 'Platform performans sorunu yasadiginizda su adimlari deneyin:\n\n1. Tarayici Onbellegi: Ctrl+Shift+Delete ile tarayici onbellegini temizleyin\n2. Sayfayi Yenileyin: F5 veya Ctrl+R ile sayfayi yeniden yukleyin\n3. Farkli Tarayici: Baska bir tarayicide deneyin (Chrome onerilir)\n4. Internet Baglantisi: Baglanti hizinizi kontrol edin (en az 2 Mbps)\n5. Eklentiler: Tarayici eklentilerini gecici olarak devre disi birakin\n6. Cihaz: Bilgisayarinizi yeniden baslatin\n\nSorun devam ediyorsa destek talebi olusturun ve su bilgileri ekleyin: hangi sayfada sorun yasandigini, ne zaman basladigini, tarayici adini ve surumunu.' },
      { q: 'Birden fazla departmanda gorev atayabilir miyim?', a: 'Evet, gorev olusturulurken birden fazla departmandan kisi secebilirsiniz. Gorev birden fazla kisiye atanabilir ve her atanan kisi gorevi kendi gorev listesinde gorur.\n\nDepartmanlar arasi gorev atamasi icin yeterli yetki seviyesine sahip olmaniz gerekir. Normalde bir kullanici yalnizca kendi departmanindaki kisilere gorev atayabilir. Birden fazla departmana atama yapmak icin en az Mudur (Seviye 6) veya ustu rolune ihtiyaciniz vardir.\n\nGorev detayinda "Atananlar" bolumunden kisileri eklweyebilir veya cikarabilirsiniz.' },
      { q: 'OperIQ analizi ne kadar gunceld ir?', a: 'OperIQ, platform verilerinizi gercek zamanli olarak kullanir. Analiz istedignizde o anki mevcut tum verileri dikkate alir. IoT verileri, gorev durumlari, stok seviyeleri ve raporlar dahil tum veriler anlik olarak OperIQ\'nun bilgi havuzuna yansir.\n\nOperIQ\'nun sunabilecegi analiz derinligi, platformda ne kadar veri bulunduguna baglidir. Platform ne kadar uzun suredir kullaniliyorsa ve ne kadar cok veri girildiyse, OperIQ o kadar detayli ve isabetli analizler uretir.\n\nGunluk fotograf analiz limiti mobil uygulamada 5 adet ile sinirlidir. Platform uzerinde ise metin bazli sorularda limit yoktur.' },
      { q: 'Excel veya CSV ile toplu veri yukleme basarisiz oluyor, ne yapmaliyim?', a: 'Toplu veri yuklemede sorun yasadiginizda su kontrolleri yapin:\n\n- Dosya Formati: Dosyanizin .xlsx veya .csv formatinda oldugundan emin olun (.xls desteklenmez)\n- Sutun Basliklari: Sablondaki sutun basliklarini degistirmeyin\n- Bos Satirlar: Veri arasinda bos satir birakmayin\n- Ozel Karakterler: Veri icerisinde beklenmedik ozel karakterler olmadigindan emin olun\n- Dosya Boyutu: Maksimum dosya boyutu 10 MB\'dir\n- Satir Limiti: Tek seferde maksimum 5000 satir yuklenebilir\n\nOnizleme ekraninda hatali satirlar kirmizi ile isaretlenir ve hata aciklamasi goruntulenir. Hatali satirlari duzelttikten sonra tekrar deneyin. OperIQ sutun eslestirme asamasinda otomatik duzeltme onerileri de sunar.' },
    ],
  },
]

const MOBILE_GUIDE_TR: Section[] = [
  {
    icon: Smartphone, title: 'Giris & Baslangic',
    items: [
      { q: 'Mobil giris nasil yapilir?', a: 'Admin tarafindan verilen giris kodu (ACT-XXXXXX) ve gecici sifre ile giris yapin. Giris ekraninda su adimlari izleyin:\n\n1. "Giris Kodu" alanina ACT-XXXXXX formatindaki kodunuzu girin\n2. "Sifre" alanina gecici sifrenizi girin\n3. "Giris Yap" butonuna basin\n4. Ilk giriste sistem sizden yeni sifre belirlemenizi isteyecektir\n5. Yeni sifrenizi girin ve onaylayin\n\nSifreniz en az 8 karakter uzunlugunda olmali, buyuk harf, kucuk harf ve rakam icermelidir. Giris kodunuzu ve sifrenizi baskasi ile paylaşmayin. Sifrenizi unutursaniz yoneticinizden yeni gecici sifre talep edin.' },
      { q: 'Uygulama ana sayfasinda ne var?', a: 'Mobil uygulama basit ve kullanimi kolay bir arayuze sahiptir. Ana bilesenler:\n\nAlt Menu (4 sekme):\n- Gorevler: Size atanan tum gorevler ve durumları\n- Formlar: Doldurmaniz gereken saha formlari\n- OperIQ Asistan: Yapay zeka sohbet ekrani\n- Profil: Kisisel bilgiler, ayarlar ve cikis\n\nUst Bar:\n- Senkronizasyon Butonu: Verileri sunucu ile esitleme (yesil = guncel, turuncu = bekleyen veri var)\n- Bildirim Zili: Yeni bildirimler ve uyarilar (kirmizi nokta = okunmamis bildirim var)\n- Sirket Logosu: Ana sayfaya donus\n\nAna ekranda ayrica gunun ozeti goruntulenir: bekleyen gorev sayisi, bugun tamamlanan gorevler ve onemli bildirimler.' },
      { q: 'Uygulamayi ana ekrana ekleme (PWA)', a: 'ActLedger mobil uygulamasi Progressive Web App (PWA) olarak calisir. Uygulama marketinden indirmeye gerek yoktur. Ana ekrana eklemek icin:\n\niPhone / Safari:\n1. ActLedger mobil adresini Safari\'de acin\n2. Alt menudeki paylasim (kare + ok) ikonuna tiklayin\n3. "Ana Ekrana Ekle" secenegini secin\n4. "Ekle" butonuna basin\n\nAndroid / Chrome:\n1. ActLedger mobil adresini Chrome\'da acin\n2. Ust menudeki uc nokta ikonuna tiklayin\n3. "Ana ekrana ekle" secenegini secin\n4. "Ekle" butonuna basin\n\nAna ekrana eklendikten sonra uygulama diger uygulamalar gibi ikon ile gorunur ve tam ekran modunda calisir.' },
      { q: 'Bildirim izinlerini ayarlama', a: 'Mobil uygulamadan anlık bildirimler alabilmek icin cihazinizin bildirim iznini vermeniz gerekir. Ilk giriste uygulama sizden bildirim izni isteyecektir.\n\nIzni vermek icin:\n- iPhone: "Izin Ver" butonuna basin. Daha sonra Ayarlar > Bildirimler > ActLedger yolundan ayarlayabilirsiniz.\n- Android: "Izin Ver" butonuna basin. Daha sonra Ayarlar > Uygulamalar > ActLedger > Bildirimler yolundan ayarlayabilirsiniz.\n\nBildirim izni verildikten sonra su durumlarda anlik bildirim alirsiniz:\n- Size yeni gorev atandiginda\n- Gorev durumu degistiginde\n- Yeni mesaj geldiginde\n- Onay bekleyen is akisi adiminiz oldugunda' },
    ],
  },
  {
    icon: ClipboardList, title: 'Gorevler',
    items: [
      { q: 'Gorevlerimi nasil gorurum?', a: '"Gorevler" sekmesinde size atanan tum aktif gorevler listelenir. Gorev listesinde her kart uzerinde su bilgiler goruntulenir:\n\n- Gorev Basligi\n- Oncelik seviyesi (renk kodu ile)\n- Teslim tarihi\n- Mevcut durum (Beklemede, Devam Ediyor, Tamamlandi)\n- Checklist ilerleme yuzdesi\n\nListeyi filtrelemek icin ust kisimdaki filtre butonlarini kullanin:\n- Tumu: Tum gorevleriniz\n- Aktif: Beklemede ve devam eden gorevler\n- Tamamlandi: Tamamlanmis gorevler\n- Geciken: Teslim tarihi gecmis gorevler (kirmizi ile isaretlenir)\n\nGorevler varsayilan olarak oncelik sirasina gore siralanir. Teslim tarihine gore siralamak icin siralama butonuna basin.' },
      { q: 'Gorev nasil tamamlanir?', a: 'Gorev tamamlama süreci adim adim su sekildedir:\n\n1. Gorev listesinden goreve tiklayin - detay sayfasi acilir\n2. Gorevin aciklama ve talimatlarini okuyun\n3. Checklist maddeleri varsa her tamamlanan adimi isaretleyin\n4. Gerekirse yorum veya not ekleyin\n5. Fotograf eklemeniz gerekiyorsa kamera ikonuyla cekin veya galeriden secin\n6. Ust kisimdaki durum alanina tiklayin\n7. "Tamamlandi" secenegini secin\n8. Onay ekraninda "Onayla" butonuna basin\n\nGorev tamamlandiginda gorev sahibine (olusturana) otomatik bildirim gonderilir. Tamamlanan gorevler "Tamamlandi" filtresinde goruntulenir. Gerekirse yonetici gorevi tekrar "Devam Ediyor" durumuna dondürebilir.' },
      { q: 'Goreve yanit ve yorum ekleme', a: 'Gorev detay sayfasinin alt kisminda yorum alani bulunur. Burada gorev hakkinda bilgi paylasabilir, soru sorabilir veya ilerleme bildirimi yapabilirsiniz.\n\nYorum eklemek icin:\n1. Gorev detay sayfasini acin\n2. "Yorum Ekle" alanina tiklayin\n3. Mesajinizi yazin\n4. Gerekirse ataç ikonuyla dosya veya fotograf ekleyin\n5. "Gonder" butonuna basin\n\nYorumlariniz gorev gecmisinde kronolojik siraya ile goruntulenir. Tum ilgili kisiler (gorev sahibi ve diger atanan kisiler) yorumunuzu bildirim olarak alir. Bu sayede gorev hakkindaki tum iletisim tek bir yerde toplanmis olur.' },
      { q: 'Goreve fotograf ekleme', a: 'Sahada calisirken gorevlere fotograf eklemek oldukca kolaydir:\n\n1. Gorev detay sayfasini acin\n2. "Fotograf Ekle" veya kamera ikonuna tiklayin\n3. Secenekler goruntulenir:\n   - Kamera: Telefonunuzun kamerasini acarak anlik fotograf cekin\n   - Galeri: Telefonunuzda kayitli bir fotografi secin\n4. Fotograf eklendikten sonra opsiyonel aciklama yaziabilirsiniz\n5. "Kaydet" ile fotografi goreve ekleyin\n\nEklenen fotograflar gorev detayinda galeri olarak goruntulenir. Fotograflar otomatik olarak sunucuya yuklenir - internet baglantisi yoksa cevrimdisi olarak saklanir ve baglanti geri geldiginde otomatik yuklenir.' },
    ],
  },
  {
    icon: FileText, title: 'Formlar',
    items: [
      { q: 'Form nasil doldurulur?', a: '"Formlar" sekmesinden doldurmaniz gereken formlari gorun. Form doldurma adimlari:\n\n1. Form listesinden ilgili form sablonunu secin\n2. Form alanlari goruntulenir - her alani siraya ile doldurun\n3. Alan tipleri: metin, sayi, tarih, tekli/coklu secim, fotograf, konum\n4. Zorunlu alanlar yildiz (*) isareti ile belirtilmistir\n5. Fotograf alani varsa kamera veya galeriden secim yapin\n6. Konum alani varsa mevcut konumunuzu otomatik ekleyin\n7. Tum alanlari doldurduktan sonra "Gonder" butonuna basin\n8. Onay ekraninda bilgileri kontrol edin ve "Onayla" ile gonderin\n\nGonderilen formlar yoneticinize bildirim olarak iletilir. Form gecmisinde daha once doldurdugunuz formlari gorebilirsiniz.' },
      { q: 'Form taslagi kaydetme', a: 'Formu hemen tamamlayamiyorsaniz taslak olarak kaydetme ozelligini kullanin:\n\n1. Formu kismi olarak doldurun\n2. Sag ustteki "Taslak Kaydet" butonuna basin\n3. Form "Taslaklarim" bolumunde goruntulenir\n4. Daha sonra taslaga tikla yarak kaldıgınız yerden devam edin\n5. Tum alanlari doldurunca "Gonder" ile gonderin\n\nTaslaklar cihazinizda ve sunucuda saklanir. Internet baglantisi olmasa bile taslak kaydetme calısır. Taslak formlari duzenleyebilir veya silebilirsiniz.' },
      { q: 'Form gecmisi ve tekrar gonderme', a: 'Daha once doldurdugunuz formlari "Form Gecmisi" bolumunde gorebilirsiniz. Gecmis formlar su bilgilerle listelenir:\n\n- Form adi ve tarihi\n- Durum: Gonderildi, Inceleniyor, Onaylandi, Reddedildi\n- Gonderilen veriler (salt okunur)\n\nBir formu tekrar doldurmak icin gecmis formun yanindaki "Tekrar Doldur" butonuna basin. Onceki yanitlar on-doldurulmus olarak goruntulenir - degistirmek istediginiz alanlari guncelleyip yeniden gonderin.\n\nReddedilen formlar icin red nedeni goruntulenir. Gerekli duzeltmeleri yaparak formu tekrar gonderebilirsiniz.' },
      { q: 'Formda fotograf ve konum ekleme', a: 'Bazi form sablonlarinda fotograf ve konum alanlari zorunlu olabilir. Bu alanlar saha calismalarinizi belgelemek icin kullanilir.\n\nFotograf Alani:\n- Kamera ikonuna tiklayin\n- "Fotograf Cek" ile kamerayi acin veya "Galeriden Sec" ile mevcut bir fotografi secin\n- Birden fazla fotograf eklemeyi destekleyen alanlarda "+" butonu ile ek fotograf ekleyin\n- Her fotograf icin opsiyonel aciklama yazabilirsiniz\n\nKonum Alani:\n- "Konumumu Ekle" butonuna tiklayin\n- Cihaziniz mevcut GPS konumunuzu alir\n- Konum adresi otomatik olarak goruntulenir\n- Konum izni vermis olmaniz gerekir' },
    ],
  },
  {
    icon: Zap, title: 'OperIQ Mobil Asistan',
    items: [
      { q: 'OperIQ\'ya nasil soru sorarim?', a: 'Alt menudeki OperIQ ikonuna tiklayin. Sohbet ekrani acilir ve yapay zeka asistanina dogal dilde soru sorabilirsiniz.\n\nOperIQ\'ya sorabilece giniz ornek sorular:\n- "Bugun benim gorevlerim nelerdir?"\n- "Departmanimdaki geciken gorevler hangileri?"\n- "Stok durumu nasil?"\n- "Bu makinenin bakim proseduru nedir?"\n- "Son haftanin rapor ozeti"\n\nOperIQ, sirketinize ozel verileri kullanarak cevap verir. Turkce veya Ingilizce soru sorabilirsiniz. Kısa ve net sorular daha isabetli yanitlar almanizi saglar.\n\nSohbet gecmisiniz saklanir - onceki konusmalarinizi kaydirarak gorebilirsiniz. "Yeni Sohbet" butonu ile temiz bir sohbet baslatabilirsiz.' },
      { q: 'Fotograf analizi nasil yapilir?', a: 'OperIQ sohbet ekraninda gorsel analiz ozelligi ile sahadaki durumlari yapay zeka ile degerlendirebilirsiniz:\n\n1. Sohbet ekraninda kamera ikonuna tiklayin\n2. "Fotograf Cek" ile kameranizi acin veya "Galeriden Sec" ile mevcut fotograf secin\n3. Fotografin ne hakkinda analiz istediginizi yazin (orn: "Bu makine panosu normal mi?", "Bu hasari degerlendir")\n4. "Gonder" butonuna basin\n5. OperIQ fotografı analiz ederek bulgulari metin olarak raporlar\n\nFotograf analizi su durumlarda faydalidir:\n- Ekipman veya makine durumu degerlendirme\n- Hasar veya ariza tespit\n- Guvenlik kontrolu\n- Stok sayimi dogrulama\n\nGunluk fotograf analiz limiti 5 adet ile sinirlidir. Limit gece yarisi sifirlanir.' },
      { q: 'Sesli komut kullanma', a: 'OperIQ sohbet ekraninda mikrofon ikonuyla sesli mesaj gonderebilirsiniz:\n\n1. Mikrofon ikonuna tiklayin ve basin\n2. Sorunuzu veya komutunuzu konusunn\n3. Birakin - sesiniz metne donusturulur\n4. Donusturulen metni kontrol edin\n5. "Gonder" ile gonderin\n\nSesli komut ozellikle elleriniz mesgulken (saha calisirken, ekipman kontrol ederken) kullanislidir. Turkce ve Ingilizce ses tanima desteklenir. Gurultulu ortamlarda net konusmaya dikkat edin.' },
      { q: 'OperIQ ile hizli islem yapma', a: 'OperIQ sadece soru cevaplamakla kalmaz, bazi islemleri de sizin adınıza yapabilir:\n\n- "Yeni gorev olustur: Depo raftlarini kontrol et" - gorev olusturma\n- "Bugunku gorevlerimi ozetle" - gorev ozeti alma\n- "Sicaklik sensoru son 24 saat grafigi" - veri sorgulama\n- "Bu haftanin raporlarini listele" - rapor sorgulama\n\nOperIQ islem yapmadan once sizden onay ister. Ornegin gorev olusturma komutunda onceligi, atamayi ve teslim tarihini sorar. Onayladiginizda islem tamamlanir.\n\nBu ozellik ile platform arayuzune gecmeden hizlica islemler yapabilirsiniz.' },
    ],
  },
  {
    icon: Map, title: 'Konum & Senkronizasyon',
    items: [
      { q: 'Konum paylasimi nasil calisir?', a: 'Mobil uygulamada konum paylasimi su sekilde calisir:\n\n1. Ilk kullanimimda uygulama konum izni ister - "Her Zaman Izin Ver" secenegini secin\n2. Konum izni verildikten sonra uygulamaniz 60 saniyede bir konumunuzu platforma gonderir\n3. Konumunuz canli harita uzerinde gercek zamanli olarak goruntulenir\n4. Profilinizde mevcut konumunuzu ve son guncelleme zamanini gorebilirsiniz\n\nKonum paylasimi hakkinda onemli bilgiler:\n- Konum verisi sadece calisma saatlerinde paylasilir\n- GPS dogrulugu iceride 10-20 metre, disarida 3-5 metre civarindadir\n- Batarya tuketimini minimize etmek icin optimize edilmistir\n- Konum paylasimini profil ayarlarindan gecici olarak durdurabilirsiniz\n- Yoneticiniz konum gecmisinizi harita uzerinde rota olarak gorebilir' },
      { q: 'Cevrimdisi calisma nasil olur?', a: 'Internet baglantisi kesildiginde mobil uygulama cevrimdisi modda calismaya devam eder:\n\nCevrimdisi yapilabilecekler:\n- Gorev listesini goruntuleme (son senkronizasyondaki hali)\n- Gorev durumu guncelleme\n- Checklist maddeleri isaretleme\n- Form doldurma ve taslak kaydetme\n- Yorum ve not ekleme\n- Fotograf cekme ve goreve ekleme\n\nTum bu islemler cihazinizda yerel olarak saklanir. Internet baglantisi geri geldiginde:\n1. Ust bardaki senkronizasyon butonu turuncu yanip soner\n2. Otomatik senkronizasyon baslar (veya butona basarak manuel baslatın)\n3. Bekleyen tum veriler sunucuya yuklenir\n4. Sunucudaki yeni veriler cihaziniza indirilir\n5. Senkronizasyon tamamlaninca buton yesile doner\n\nCevrimdisi modda yapilan islemlerde tarih ve saat bilgisi cihaz saatine gore kaydedilir.' },
      { q: 'Batarya ve veri kullanimi', a: 'Mobil uygulamanin batarya ve veri kullanimini optimize etmek icin:\n\nBatarya Tasarrufu:\n- Konum guncelleme sikligi otomatik olarak optimize edilir\n- Arkaplanda minimum batarya tuketimi (gunluk ~%3-5)\n- Dusuk batarya modunda konum guncelleme sikligi azalir\n\nMobil Veri Kullanimi:\n- Uygulama aylik yaklasik 50-100 MB veri kullanir (fotografsiz)\n- Fotograflar WiFi baglantisi tercih edilerek yuklenir\n- Ayarlardan "Sadece WiFi ile Senkronize Et" secenegini acabilirsiniz\n- Cevrimdisi modda veri kullanimi sifirdir\n\nBatarya veya veri kullaniminda anormal artis fark ederseniz uygulamayi kapatip tekrar acin veya cihazinizi yeniden baslatin.' },
      { q: 'Senkronizasyon sorunlarini giderme', a: 'Senkronizasyon sorunlari yasadiginizda su adimlari deneyin:\n\n1. Internet Baglantisi: WiFi veya mobil veri baglantinizin aktif oldugundan emin olun\n2. Manuel Senkronizasyon: Ust bardaki senkronizasyon butonuna basin\n3. Uygulamayi Yeniden Baslatın: Uygulamayi tamamen kapatip tekrar acin\n4. Cihaz Depolama: Cihazinizda yeterli bos alan oldugundan emin olun (en az 100 MB)\n5. Uygulama Guncelleme: Tarayicidaki once bellegi temizleyip sayfayi yeniden yukleyin\n\nSenkronizasyon durumu:\n- Yesil: Tum veriler guncel\n- Turuncu: Bekleyen veriler var, senkronizasyon devam ediyor\n- Kirmizi: Senkronizasyon hatasi - ustteki adimlari deneyin\n\nSorun devam ediyorsa yoneticinize veya teknik desteğe bildirin.' },
    ],
  },
  {
    icon: Bell, title: 'Mobil Bildirimler',
    items: [
      { q: 'Push bildirimler nasil calisir?', a: 'Mobil uygulamada push bildirimler ile onemli olaylardan aninda haberdar olursunuz.\n\nBildirim alacaginiz durumlar:\n- Size yeni gorev atandiginda\n- Gorev durumu degistiginde\n- Gorev yorumu eklendiginde\n- Yeni mesaj geldiginde\n- Is akisinda onay beklediginde\n- IoT alarm tetiklendiginde (yetkiniz varsa)\n\nBildirimlere tikla yarak dogrudan ilgili sayfaya yonlendirilirsiniz. Ornegin gorev bildirimine tiklamak gorev detay sayfasini acar.\n\nBildirim almiyorsaniz:\n1. Cihaz ayarlarindan bildirim izninin verildiginden emin olun\n2. "Rahatsiz Etmeyin" modunun kapali oldugundan emin olun\n3. Uygulamamin arka planda calismasina izin verildiginden emin olun' },
      { q: 'Bildirim sesini ve titresimini ayarlama', a: 'Bildirim ses ve titresim ayarlarini cihazinizin ayarlarindan yapabilirsiniz:\n\niPhone:\n1. Ayarlar > Bildirimler > ActLedger\n2. Ses, Rozet ve Banner ayarlarini yapin\n3. Kilit ekraninda gorunup gorunmeyecegini secin\n\nAndroid:\n1. Ayarlar > Uygulamalar > ActLedger > Bildirimler\n2. Bildirim kategorilerini ayrı ayrı ayarlayin\n3. Ses, titresim ve oncelik seceneklerini belirleyin\n\nGece saatlerinde rahatsiz edilmemek icin cihazinizin "Rahatsiz Etmeyin" zamanlama ozelligini kullanabilirsiniz. Bu sayede mesai disinda bildirim almayı durdurabilirsiniz.' },
    ],
  },
  {
    icon: Settings, title: 'Profil & Ayarlar',
    items: [
      { q: 'Profil bilgilerini goruntuleme', a: '"Profil" sekmesinde su bilgilerinizi gorebilirsiniz:\n\n- Ad ve Soyad\n- E-posta adresi\n- Departman ve Rol\n- Giris kodu (ACT-XXXXXX)\n- Mevcut konum (konum paylasimi aktifse)\n- Son senkronizasyon zamani\n- Uygulama surumu\n\nProfil fotografinizi degistirmek icin fotograf alanina tiklayin ve kamera veya galeriden secim yapin.' },
      { q: 'Sifre degistirme', a: 'Sifrenizi degistirmek icin:\n\n1. "Profil" sekmesine gidin\n2. "Sifre Degistir" butonuna basin\n3. Mevcut sifrenizi girin\n4. Yeni sifrenizi girin (en az 8 karakter, buyuk harf, kucuk harf, rakam)\n5. Yeni sifrenizi tekrar girerek onaylayin\n6. "Kaydet" butonuna basin\n\nSifre basariyla degistirildiginde onay mesaji goruntulenir. Bir sonraki girista yeni sifrenizi kullanin. Mevcut oturumunuz devam eder.\n\nSifrenizi unutursaniz giris ekranindaki "Sifremi Unuttum" linkini kullanin veya yoneticinizden gecici sifre talep edin.' },
      { q: 'Dil ve bildirim tercihleri', a: 'Profil ayarlarindan dil ve bildirim tercihlerinizi yapilandirabilirsiniz:\n\nDil Secimi:\n- Turkce veya Ingilizce arasinda secim yapin\n- Dil degisikligi aninda uygulanir\n\nBildirim Tercihleri:\n- Gorev bildirimleri: Acik/Kapali\n- Mesaj bildirimleri: Acik/Kapali\n- IoT alarm bildirimleri: Acik/Kapali\n- Sistem duyurulari: Acik/Kapali\n\nBu ayarlar sadece mobil bildirimler icindir. Platform (web) bildirimleri ayri olarak profil sayfasindan ayarlanir.' },
      { q: 'Guvenli cikis yapma', a: 'Uygulamadan guvenli cikis yapmak icin:\n\n1. "Profil" sekmesine gidin\n2. Sayfanin altindaki "Cikis Yap" butonuna basin\n3. Onay ekraninda "Evet, Cikis Yap" butonuna basin\n\nCikis yapildiginda:\n- Oturumunuz sonlandirilir\n- Yerel veriler silinir\n- Konum paylasimi durur\n- Giris ekranina yonlendirilirsiniz\n\nOnemli: Paylas ilan veya baskasinin cihazindan giris yaptiyseniz isleriniz bittiginde mutlaka cikis yapin. Cikis yapmadan cihazi baskasina vermeyin.' },
    ],
  },
]

export default function UserGuide() {
  const { lang } = useLanguage()
  const navigate = useNavigate()
  const [tab, setTab] = useState<'platform' | 'mobile'>('platform')
  const [openSections, setOpenSections] = useState<Set<number>>(new Set([0]))
  const [navTarget, setNavTarget] = useState<string | null>(null)

  const sections = tab === 'platform' ? PLATFORM_GUIDE_TR : MOBILE_GUIDE_TR

  const toggleSection = (idx: number) => {
    setOpenSections(prev => {
      const next = new Set(prev)
      next.has(idx) ? next.delete(idx) : next.add(idx)
      return next
    })
  }

  return (
    <div className="space-y-5">
      <style>{`@keyframes bounceRight { 0%, 100% { transform: translateX(0); } 50% { transform: translateX(6px); } } .animate-bounce-right { animation: bounceRight 0.6s ease-in-out 3; }`}</style>
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-[18px] font-bold text-zinc-900 tracking-tight flex items-center gap-2">
            <BookOpen size={20} className="text-cyan-600" />
            {lang === 'tr' ? 'Kullanim Kilavuzu' : 'User Guide'}
          </h2>
          <p className="text-[12px] text-zinc-400 mt-0.5">
            {lang === 'tr' ? 'ActLedger platformunu ve mobil uygulamayi nasil kullanacaginizi ogrenin' : 'Learn how to use ActLedger platform and mobile app'}
          </p>
        </div>
      </div>

      {/* Tab switch */}
      <div className="flex gap-2">
        <button type="button" onClick={() => { setTab('platform'); setOpenSections(new Set([0])) }}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-[13px] font-bold transition-all ${tab === 'platform' ? 'bg-cyan-50 text-cyan-700 border-2 border-cyan-200' : 'bg-white border-2 border-zinc-200 text-zinc-600 hover:border-zinc-300'}`}>
          <Monitor size={16} /> {lang === 'tr' ? 'Platform Kilavuzu' : 'Platform Guide'}
        </button>
        <button type="button" onClick={() => { setTab('mobile'); setOpenSections(new Set([0])) }}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-[13px] font-bold transition-all ${tab === 'mobile' ? 'bg-violet-50 text-violet-700 border-2 border-violet-200' : 'bg-white border-2 border-zinc-200 text-zinc-600 hover:border-zinc-300'}`}>
          <Smartphone size={16} /> {lang === 'tr' ? 'Mobil Kilavuz' : 'Mobile Guide'}
        </button>
      </div>

      {/* Sections */}
      <div className="space-y-2">
        {sections.map((section, idx) => {
          const isOpen = openSections.has(idx)
          return (
            <div key={idx} className="card overflow-hidden">
              <button type="button" onClick={() => toggleSection(idx)}
                className="w-full flex items-center gap-3 px-5 py-4 text-left hover:bg-zinc-50 transition-colors">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${tab === 'platform' ? 'bg-cyan-100' : 'bg-violet-100'}`}>
                  <section.icon size={16} className={tab === 'platform' ? 'text-cyan-600' : 'text-violet-600'} />
                </div>
                <span className="text-[14px] font-bold text-zinc-800 flex-1">{section.title}</span>
                <span className="text-[11px] text-zinc-400 mr-2">{section.items.length} konu</span>
                {isOpen ? <ChevronDown size={16} className="text-zinc-400" /> : <ChevronRight size={16} className="text-zinc-400" />}
              </button>
              {isOpen && (
                <div className="px-5 pb-4 space-y-3 border-t border-zinc-100 pt-3">
                  {section.items.map((item, i) => (
                    <div key={i} className="pl-11">
                      <p className="text-[13px] font-semibold text-zinc-700 mb-1">{item.q}</p>
                      <p className="text-[12px] text-zinc-500 leading-relaxed whitespace-pre-line">{item.a}</p>
                    </div>
                  ))}
                  {section.path && (
                    <div className="pl-11 pt-2">
                      <button type="button"
                        onClick={(e) => { e.stopPropagation(); setNavTarget(section.path!); setTimeout(() => navigate(section.path!), 800) }}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg text-[12px] font-bold transition-all hover:shadow-md"
                        style={{ background: tab === 'platform' ? '#ecfeff' : '#f5f3ff', color: tab === 'platform' ? '#0891b2' : '#7c3aed', border: `1px solid ${tab === 'platform' ? '#a5f3fc' : '#ddd6fe'}` }}>
                        <ArrowRight size={14} className={navTarget === section.path ? 'animate-bounce-right' : ''} />
                        {lang === 'tr' ? 'Bu sayfaya git' : 'Go to this page'}
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
